### ISSUE TITLE
Investigate X11 forwarding as opposed to VNC

### ISSUE THREAD

**Issue by mtscout6** [elgalu/docker-selenium#10]
See the IRC conversation about this: https://botbot.me/freenode/docker-library/2014-11-06/?tz=America/Denver

The appeal is that this will allow us to derive from the official Ubuntu image and strictly run one process, which will also help in getting this image to be the "official" image for selenium as it would adhere to better docker principles.

**Comment by elgalu** [comment]
Reopening this since I'm interested in getting this fixed in this repo also.

**Comment by elgalu** [comment]
TODO: take some ideas from:

- Xpra is 'screen for X', and more: it allows you to run X programs, usually on a remote host and direct their display to your local machine. It also allows you to display existing desktop sessions remotely.
Xpra has osx/win/linux clients:
    https://www.xpra.org/dists/vivid/main/binary-amd64/
    https://www.xpra.org/dists/osx/x86/
https://www.xpra.org/trac/wiki/Usage#AccesswithoutSSH

- In the context of Xpra, Xdummy allows us to use a better, more up to date X11 display server
http://xpra.org/trac/wiki/Xdummy

https://github.com/mccahill/docker-eclipse-novnc

https://github.com/bencawkwell/dockerfile-xpra/blob/master/Dockerfile#L18

https://github.com/rogaha/docker-desktop/blob/master/startup.sh#L7
https://github.com/rogaha/docker-desktop/blob/master/Dockerfile#L38

**Comment by elgalu** [comment]
I lost interest in following the `strictly run one process` rule as the current setup has proved successful in my company so closing this one.
