### ISSUE TITLE
What's the root's password in docker image

### ISSUE THREAD

**Issue by luisxiaomai** [elgalu/docker-selenium#104]
Hi,

The default user is application, can you tell me the password of root?

B.R.
Luis

**Comment by elgalu** [comment]
The `application` user is [passwordless sudo/root](https://github.com/elgalu/docker-selenium/blob/2.53.0r/Dockerfile#L232), there are no passwords set at all.

**Comment by luisxiaomai** [comment]
@elgalu, execute sudo root said commend not found.

**Comment by luisxiaomai** [comment]
Thanks
