### ISSUE TITLE
where do you put your test script ?

### ISSUE THREAD

**Issue by medyagh** [elgalu/docker-selenium#105]
I have a python selenium script, how can I tell it to run that ?

**Comment by elgalu** [comment]
### Need 2 things

#### Point to the right selenium
In your python test, see for example [python_test.py](https://github.com/elgalu/docker-selenium/blob/2.53.0s/test/python_test.py#L30), you point to the running selenium host with `SELENIUM_HUB_HOST` and port with `SELENIUM_HUB_PORT`

#### Point to the right tested page
If you are testing a [public page for example](https://github.com/elgalu/docker-selenium/blob/2.53.0s/test/python_test.py#L74) this is the easiest use case as it doesn't matter where the selenium server is.
But if you are running your tested app in localhost then localhost is different inside the docker container versus the host machine that runs docker, this is a network detail.
You can avoid thinking about this by adding `--net=host` and `--pid=host` to `docker run` see [pid section](https://github.com/elgalu/docker-selenium#pid) in the README.

**Comment by medyagh** [comment]
I understand this project is for cluster of selenium servers but all I am interested in is, I have a python selenium script that does chores for me. I wanna run it occasionally without interfering my desktop (run in background and no need to set up my machine) .


am I still in the right project ? or that functionality is out of scope of this project ? if yes how can I make one docker container do it all.

**Comment by medyagh** [comment]
@elgalu btw I am curious why the python test is only in the older commits and was removed later?

**Comment by elgalu** [comment]
It was not removed
https://github.com/elgalu/docker-selenium/blob/master/test/python_test.py

**Comment by elgalu** [comment]
Did that help?

**Comment by elgalu** [comment]
No response so closing...
