### ISSUE TITLE
building local creates image without REPOSITORY and TAG set

### ISSUE THREAD

**Issue by mmolhoek** [elgalu/docker-selenium#107]
I am working on Ubuntu 16.04 LTS

When building the image local after cloning the repo (as explained in the readme):
`docker build -t="elgalu/docker-selenium:local" .`
and I do a:
`docker images`
I get 
```
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
<none>                              <none>              6a76905cbd0c        25 seconds ago      2.872 GB
```
I fixed it afterwards with:
`docker tag 6a76905cbd0c elgalu/docker-selenium:local`
after that, docker images gives:
```
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
elgalu/docker-selenium              local               6a76905cbd0c        2 minutes ago       2.872 GB
```
I have no idea why the tag is not correct in the first place. thought i'd let you know :)

**Comment by elgalu** [comment]
Try `-t elgalu/docker-selenium:local` instead of `-t="elgalu/docker-selenium:local"` algo upgrade docker just in case.

**Comment by elgalu** [comment]
Did that help?

**Comment by elgalu** [comment]
No response so closing...
