### ISSUE TITLE
Problem with dbus-launch

### ISSUE THREAD

**Issue by ThomasBracher** [elgalu/docker-selenium#11]
I'm working with selenium 2.43.1 and Firefox fails with this error message:
````
(firefox:122): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
//bin/dbus-launch terminated abnormally without any error message
````
Seems that `dbus-launch` is now in package `dbus-x11` (https://bugs.launchpad.net/ubuntu/+source/dbus/+bug/118919). I Haven't managed to make it work again though, i'll propose a PR once i found a viable solution.

**Comment by elgalu** [comment]
`dbus-x11` is already part of the Dockerfile: https://github.com/elgalu/docker-selenium/blob/7457f1768653df2625d5a6d28c085e797885351e/Dockerfile#L258

Try upgrading to latest:

```
docker run -p 4444:4444 -p 5900:5900 -e SCREEN_WIDTH=1550 -e SCREEN_HEIGHT=1110 -e VNC_PASSWORD=secret elgalu/selenium:v2.45.0-berlin5
```

**Comment by ThomasBracher** [comment]
selenium 2.45 works fine
