### ISSUE TITLE
Cannot start hub and nodes in Mac with Docker Beta

### ISSUE THREAD

**Issue by diemol** [elgalu/docker-selenium#110]
In docker beta for Mac, Version 1.12.0-rc2-beta17 (build: 9779)

The commands shown in the following link, 
https://github.com/elgalu/docker-selenium/blob/master/docs/hub_and_nodes.md

Do not work.

Seems it is related to this issue:
https://github.com/docker/docker/issues/22753

Cheers,

**Comment by elgalu** [comment]
Should now be fixed through https://github.com/elgalu/docker-selenium/blob/master/docs/docker-compose.md#compose

**Comment by diemol** [comment]
Works now after following the instructions.
