### ISSUE TITLE
Help on run selenium test in one container

### ISSUE THREAD

**Issue by luisxiaomai** [elgalu/docker-selenium#113]
Hi guys,

I want to run selenium test inside your docker-selenium with a dockerfile, 
```
FROM  elgalu/selenium
COPY / /selenium/
RUN chmod +x /selenium/run.sh
ENTRYPOINT ["/selenium/run.sh"]
```
Then I built this image with above dockerfile and then run the container. But I found it can not start default selenium server and other servers which you wrote in entry.sh, it only will run /selenium/run.sh.

Can you give some guide how to do this kind testing in one container?

B.R.
Luis

**Comment by elgalu** [comment]
Please follow this example for that: https://github.com/elgalu/docker-selenium/blob/master/docs/docker-compose.md#usage

**Comment by luisxiaomai** [comment]
@elgalu , it works for I run my selenium test in another container which will connect to selenium server in another container. It should be similar to what you mentioned above.

But my help is on how to do test in only one container, both for selenium test and selenium server+browser. 
I tried to write a dockerfile which was based on elgalu/selenium,then I built this image with this dockerfile and then run the container. I find my selenium test will run, but selenium hub , nodes, videso are totally not running. But if I remove the entrypoint ["selenium/run.sh"], I found these server will up and running. How can I run this dockerfile with both server and selenium run?

**Comment by elgalu** [comment]
Ah ok, then you need to change `FROM docker pull elgalu/selenium` to `FROM elgalu/selenium` and don't mess with the `ENTRYPOINT` nor the `CMD` please see this example for NodeJS apps: https://gist.github.com/elgalu/b41ac82652d3eba21bbe59fa061aadd2

So you need to start it as shown in https://github.com/elgalu/docker-selenium#usage

Once is started you can run your tests locally with an additional command, e.g.

```sh
docker exec -ti grid gulp test
```

**Comment by luisxiaomai** [comment]
@elgalu , thanks for your guide.
