### ISSUE TITLE
NoVNC should connect directly when no password is required

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#115]
NoVNC should connect directly when no password is required, i.e. when `VNC_PASSWORD=no`

**Comment by outerpasta** [comment]
This is working already for me by using the vnc_auto.html page, for example:
```
docker run --name grid -d -e NOVNC=true -e VNC_PASSWORD=no -p 6080:26080 elgalu/selenium \ 
   && docker exec grid wait_all_done 30s \
   && open http://localhost:6080/vnc_auto.html
```

**Comment by elgalu** [comment]
awesome @outerpasta I didn't know about `vnc_auto.html` and only used `vnc.html` thanks ! :)

If you want you can [edit the README](https://github.com/elgalu/docker-selenium/edit/master/README.md) and change `vnc.html` with `vnc_auto.html` and generate a pull request ;)
