### ISSUE TITLE
docs/make.md setup has hidden requisites in Mac

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#117]
- Install brew
- Install wget (with brew)
- Install https://github.com/caskroom/homebrew-cask to install VNC easily.

reported by @diemol

**Comment by diemol** [comment]
Any updates?

**Comment by elgalu** [comment]
This is no longer relevant as we now prefer our new product [Zalenium](https://github.com/zalando/zalenium) plus launching it through our [one-line installer](https://github.com/dosel/t#zalenium-one-liner-installer)

```sh
curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | bash -s start
```
