### ISSUE TITLE
Rename the project?

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#118]
https://www.andreas-jung.com/contents/dont-use-docker-in-github-repo-names-or-as-twitter-handle

**Comment by conversica-aaronpa** [comment]
Selenium project was named referencing mercury poisoning antidote (HP Mercury that is), docker has fish reference, tuna are known to have suffered from mercury accumulation... HealthyTuna?
Current name made it easy to find project, maybe just move docker from front, throw in "grid" somewhere.

**Comment by elgalu** [comment]
We found no further reasons to rename this project, the name will stay unless Docker Inc. complains.
