### ISSUE TITLE
Microsoft Windows support?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [elgalu/docker-selenium#122]
Hi, from the readme it's not very clear does DOCKERSELENIUM support Microsoft Windows (7, 10, ...)?

I mean can this repo be used on a Windows machine/host or does it require a Linux host?

Cheers
Tset

**Comment by elgalu** [comment]
In theory should also work from a Windows host as docker abstract you from that.

However I'm only testing this project on Linux and Windows so feel free to try it out on Windows and if you do please let us know how it went.

And please use docker latest with native Windows support to do so:
https://docs.docker.com/docker-for-windows/

**Comment by Tset-Noitamotua** [comment]
I have tried a lot of other repos related to Docker here on Github (before "docker-for-windows" existed). Unfortunately most of them (which were not explicitly build with Windows in mind) did not work out of the box. So just a few months ago Docker & Crossplattform was really just theory - at least for what I have tried.

But I am about to update my Windows machines to Windows 10 and am very excited how docker-for-windows will work out.

I'll be back ;-)

**Comment by elgalu** [comment]
Awesome, I'm now curious to see if it works!

**Comment by elgalu** [comment]
So did it work @Tset-Noitamotua ?

**Comment by Tset-Noitamotua** [comment]
@elgalu  Hey sorry for delay, I did not checked it yet but it is still on my TODO list. Please leave this one open.

**Comment by elgalu** [comment]
updates?

**Comment by Tset-Noitamotua** [comment]
work in progress 
hope to give you feedback until end of this week

**Comment by Tset-Noitamotua** [comment]
logs to my diary ...

What I have done:

Step1 (duration: some minutes):
```cmd
cd "C:\Users\ME\OneDrive\_GITHUB\docker_payground\docker_selenium"
docker pull elgalu/selenium
C:\Users\ME\OneDrive\_GITHUB\docker_payground\docker_selenium>
```

Step 2 (duration: ~ one second! amazing!):

```cmd
C:\Users\ME\OneDrive\_GITHUB\docker_payground\docker_selenium>docker run -d --name=grid -p 4444:24444 -p 5900:25900 --shm-size=1g elgalu/selenium
968099dd9370de7f86089fa474070b0ea2c67a274123c957bfcb6785087f2414
```

Step 3:

```
C:\Users\ME\OneDrive\_GITHUB\docker_payground\docker_selenium>docker exec grid wait_all_done 30s
Waiting for docker-selenium to be ready...

Container docker internal IP: 172.17.0.2
Note if you are in Mac (OSX) 'boot2docker ip' or 'docker-machine ip default' will tell you the relevant IP
Selenium all done and ready for testing!
```

Step 4:
- open `http://localhost:4444/grid/console` in Chrome. Grid Console is running:
    
![image](https://cloud.githubusercontent.com/assets/5635462/21482638/21c96afc-cb77-11e6-8a89-49597fe0a433.png)

- open `http://localhost:4444/wd/hub` in Chrome:

    ```
    {"status":13,"value":{"class":"java.lang.NullPointerException","stackTrace":
    [
    {"fileName":"ExternalSessionKey.java","className":"org.openqa.grid.internal.ExternalSessionKey","methodName":"fromWebDriverRequest","lineNumber":77},
    {"fileName":"WebDriverRequest.java","className":"org.openqa.grid.web.servlet.handler.WebDriverRequest","methodName":"extractSession","lineNumber":62},
    {"fileName":"RequestHandler.java","className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"getSession","lineNumber":239},
    {"fileName":"RequestHandler.java","className":"org.openqa.grid.web.servlet.handler.RequestHandler","methodName":"process","lineNumber":120},
    {"fileName":"DriverServlet.java","className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"process","lineNumber":83},
    {"fileName":"DriverServlet.java","className":"org.openqa.grid.web.servlet.DriverServlet","methodName":"doGet","lineNumber":61},
    {"fileName":"HttpServlet.java","className":"javax.servlet.http.HttpServlet","methodName":"service","lineNumber":687},
    {"fileName":"HttpServlet.java","className":"javax.servlet.http.HttpServlet","methodName":"service","lineNumber":790},
    {"fileName":"ServletHolder.java","className":"org.seleniumhq.jetty9.servlet.ServletHolder","methodName":"handle","lineNumber":808},
    {"fileName":"ServletHandler.java","className":"org.seleniumhq.jetty9.servlet.ServletHandler","methodName":"doHandle","lineNumber":587},
    {"fileName":"SessionHandler.java","className":"org.seleniumhq.jetty9.server.session.SessionHandler","methodName":"doHandle","lineNumber":221},
    {"fileName":"ContextHandler.java","className":"org.seleniumhq.jetty9.server.handler.ContextHandler","methodName":"doHandle","lineNumber":1127},
    {"fileName":"ServletHandler.java","className":"org.seleniumhq.jetty9.servlet.ServletHandler","methodName":"doScope","lineNumber":515},
    {"fileName":"SessionHandler.java","className":"org.seleniumhq.jetty9.server.session.SessionHandler","methodName":"doScope","lineNumber":185},
    {"fileName":"ContextHandler.java","className":"org.seleniumhq.jetty9.server.handler.ContextHandler","methodName":"doScope","lineNumber":1061},
    {"fileName":"ScopedHandler.java","className":"org.seleniumhq.jetty9.server.handler.ScopedHandler","methodName":"handle","lineNumber":141},
    {"fileName":"HandlerWrapper.java","className":"org.seleniumhq.jetty9.server.handler.HandlerWrapper","methodName":"handle","lineNumber":97},
    {"fileName":"Server.java","className":"org.seleniumhq.jetty9.server.Server","methodName":"handle","lineNumber":499},
    {"fileName":"HttpChannel.java","className":"org.seleniumhq.jetty9.server.HttpChannel","methodName":"handle","lineNumber":310},
    {"fileName":"HttpConnection.java","className":"org.seleniumhq.jetty9.server.HttpConnection","methodName":"onFillable","lineNumber":257},
    {"fileName":"AbstractConnection.java","className":"org.seleniumhq.jetty9.io.AbstractConnection$2","methodName":"run","lineNumber":540},
    {"fileName":"QueuedThreadPool.java","className":"org.seleniumhq.jetty9.util.thread.QueuedThreadPool","methodName":"runJob","lineNumber":635},
    {"fileName":"QueuedThreadPool.java","className":"org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3","methodName":"run","lineNumber":555},
    {"fileName":"Thread.java","className":"java.lang.Thread","methodName":"run","lineNumber":745}
    ]
    }}
    ```


I guess here I stuck. 

Any ideas?

**Comment by Tset-Noitamotua** [comment]
Is Java required to be installed on localhost?

**Comment by Tset-Noitamotua** [comment]
wait ... just changed my test to use Chrome and it worked!!!!

I will conduct further test and report again.

**Comment by elgalu** [comment]
Awesome! So it works with Chrome and fails with Firefox?

**Comment by Tset-Noitamotua** [comment]
Yes. But I heard that there are known issues with latests Firefox and Selenium(?) so may be nothing to worry about.

Is there a way to control the version of Firefox to be used?

**Comment by elgalu** [comment]
For Selenium 2 the current Firefox version being used is [47.0.1](https://github.com/elgalu/docker-selenium/blob/3.0.1-p3/Dockerfile#L562) which should work fine

If you use Selenium 3 then yes, there are still issues and it will use latest, right now is [50.1.0](https://github.com/elgalu/docker-selenium/blob/3.0.1-p3/Dockerfile#L550)

You can follow those links and edit the file and build the image yourself to use another version.

**Comment by elgalu** [comment]
Closing as this seems to be working. Please re-open if you experience a problem.
