### ISSUE TITLE
Firefox ESR

### ISSUE THREAD

**Issue by arthurlm44** [elgalu/docker-selenium#126]
It would be awesome if I could specify a Firefox version via an env.
It looks like this used to be a feature but is no longer supported. Any way it could be brought back?
#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`
  Linux xenial-base 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`
#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`
#### Docker-Compose

_(if using docker-compose)_
- [x] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

**Comment by elgalu** [comment]
True, so the code is still there but is commented:
https://github.com/elgalu/docker-selenium/blob/3.0.1a/Dockerfile#L533

I've never included ESR versions though, I guess you could modify that source and re-build the image in the meantime.

I would like to add this functionality in the future along with https://github.com/elgalu/docker-selenium/issues/35 but no ETA at the moment.

**Comment by elgalu** [comment]
Closing as this is more appropriate for users with the specific need to build the image on their own.
