### ISSUE TITLE
Issue while builing ( docker build -t selenium .) at step 87

### ISSUE THREAD

**Issue by learner07** [elgalu/docker-selenium#127]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`
- Linux shanky-Lenovo-B40-70 4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`
- Yes, I have latest image

- [x] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.
- NA

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`
- Docker version 1.12.2, build bb80604

- [x] If I don't have latest version of docker I will specify which version with `docker --version` output
- NA

#### Docker-Compose
_(if using docker-compose)_

- [x] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

Not using docker compose

- [x] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output
- NA

Sorry I am new to docker. While building, it is failing at step 87 with below error:

Step 86 : RUN sudo touch /capabilities.json   && sudo chown ${NORMAL_USER}:${NORMAL_GROUP} /capabilities.json   && generate_capabilities_json > /capabilities.json   && cp /capabilities.json ${NORMAL_USER_HOME}/capabilities.json   && cp /capabilities.json ${NORMAL_USER_HOME}/capabilities   && cp /capabilities.json ${NORMAL_USER_HOME}/caps.json   && cp /capabilities.json ${NORMAL_USER_HOME}/caps   && mkdir -p ${NORMAL_USER_HOME}/.vnc   && mkdir -p ${VIDEOS_DIR}   && sudo ln -s ${VIDEOS_DIR} /   && mkdir -p ${NORMAL_USER_HOME}/.ssh   && touch ${NORMAL_USER_HOME}/.ssh/authorized_keys   && chmod 700 ${NORMAL_USER_HOME}/.ssh   && chmod 600 ${NORMAL_USER_HOME}/.ssh/authorized_keys   && sudo mkdir -p ${LOGS_DIR}   && sudo mkdir -p ${RUN_DIR}   && sudo chown -R ${NORMAL_USER}:${NORMAL_GROUP} ${SEL_HOME}   && sudo chown -R ${NORMAL_USER}:${NORMAL_GROUP} ${NORMAL_USER_HOME}   && sudo chown -R ${NORMAL_USER}:${NORMAL_GROUP} ${LOGS_DIR}   && sudo chown -R ${NORMAL_USER}:${NORMAL_GROUP} ${RUN_DIR}   && sudo chown -R ${NORMAL_USER}:${NORMAL_GROUP} /etc/supervisor   && sudo chown -R ${NORMAL_USER}:${NORMAL_GROUP} /test   && sudo mkdir -p /tmp/.X11-unix /tmp/.ICE-unix   && sudo chmod 1777 /tmp/.X11-unix /tmp/.ICE-unix   && sudo mkdir -p /var/run/sshd   && sudo chmod 744 /var/run/sshd   && echo ""
 ---> Using cache
 ---> b8d2b0981c78
**Step 87 : ADD scm-source.json /
lstat scm-source.json: no such file or directory**

Please let me know if anything else is required

**Comment by elgalu** [comment]
Sorry about that, you need to create a file named `scm-source.json` 
An empty one is ok: `touch scm-source.json`

You can use the generator script also: `./host-scripts/gen-scm-source.sh`

**Comment by learner07** [comment]
@elgalu : Thank you for the quick response.

I created empty file using ``` touch scm-source.json ``` and I was able to build.

``` 
Step 87 : ADD scm-source.json /
 ---> c7afc784c8ee
Removing intermediate container 8de73d10f4d3
Step 88 : WORKDIR ${NORMAL_USER_HOME}
 ---> Running in 56057f6c52db
 ---> 204874674773
Removing intermediate container 56057f6c52db
Step 89 : CMD entry.sh
 ---> Running in 94f75f5f1633
 ---> b46d2892fec7
Removing intermediate container 94f75f5f1633
Successfully built b46d2892fec7
``` 

Cheers!
