### ISSUE TITLE
connect several nodes (containers) to remote hub?

### ISSUE THREAD

**Issue by royv-perion** [elgalu/docker-selenium#135]
Hi,

Is there an option to connect several containers to a remote hub (on separate machine) ?
In the official docker-selenium I could achieve this until version 3.0.0 , but since then it doesn't work anymore. 

my desired configuration:
hub (not from a docker but could be) on one Linux machine
browser containers (nodes) on separate Linux machines (N containers on each machine).
all nodes on all machines should connect to the same central Hub.
all node machines (hosts) and the hub machine are on the same LAN.

thanks,
Roy.

**Comment by elgalu** [comment]
Yes is possible, see `-e SELENIUM_HUB_HOST="hub.seleniums"` and `-e SELENIUM_NODE_HOST="{{CONTAINER_IP}}"` at:

https://github.com/elgalu/docker-selenium/blob/master/docs/hub_and_nodes_alternatives.md#chrome

You may need to read that whole doc

**Comment by royv-perion** [comment]
thanks, i'll try it and post follow up.

**Comment by royv-perion** [comment]
Hi,

i cannot understand how the Node "knows" about the existence of the "seleniums" virtual network create on the hub machine (its a separated VM).

so i'm puzzeled how to launch the node on the other VM:
docker run -d --name=node1_ch --net=**seleniums** \
  -e GRID=false -e CHROME=true -e FIREFOX=false \
  -e VNC_START=false -e PICK_ALL_RANDMON_PORTS=true \
  -e SELENIUM_HUB_PORT=4444 -e SELENIUM_HUB_HOST="hub.seleniums" \
  -e SELENIUM_NODE_HOST="{{CONTAINER_IP}}" \
  --shm-size=1g \
  elgalu/selenium

ideas?

**Comment by elgalu** [comment]
`SELENIUM_HUB_HOST` can be any host or IP address, you don't need to use `--net=seleniums`

**Comment by royv-perion** [comment]
worked! thanks elgalu.
