### ISSUE TITLE
Saucelabs sauceconnect VPN in the container failed due to certificate Error

### ISSUE THREAD

**Issue by StephaneColson** [elgalu/docker-selenium#136]
#### Operating System
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

#### Image version
- elgalu/selenium:3.0.1i

#### Docker version
- Docker version 1.12.2, build bb80604

#### Docker-Compose
docker-compose version 1.6.0, build d99cad6

In the selenium-grid container, the saucelab tunnel fails with the error **ERROR: connecting to https://saucelabs.com/versions.json: Peer certificate cannot be authenticated with given CA certificates, reply: [empty].**

Here are the logs retrieved in 

> $ sc --doctor -u <user> -k <key>
> 1 Dec 10:20:24 - Sauce Connect 4.4.1, build 2976 c1c1e98
> 1 Dec 10:20:24 - Using CA certificate bundle /etc/ssl/certs/ca-certificates.crt.
> 1 Dec 10:20:24 - Using CA certificate verify path /etc/ssl/certs.
> 1 Dec 10:20:24 - Calling the doctor
> INFO: checking if saucelabs.com can be resolved
> INFO: resolving 'saucelabs.com' using default system settings...
> INFO: resolved to '162.222.75.243'
> INFO: resolving 'saucelabs.com' using DNS server '127.0.0.11'...
> INFO: resolved to '162.222.75.243'
> INFO: checking 'saucelabs.com' in hosts file...
> INFO: resolved to '162.222.73.28'
> WARNING: your hosts file contains an entry for saucelabs.com.
> WARNING: only do this if instructed by Sauce Labs support.
> INFO: checking if maki76100.miso.saucelabs.com can be resolved
> INFO: resolving 'maki76100.miso.saucelabs.com' using default system settings...
> INFO: resolved to '162.222.76.100'
> INFO: resolving 'maki76100.miso.saucelabs.com' using DNS server '127.0.0.11'...
> INFO: resolved to '162.222.76.100'
> INFO: checking 'maki76100.miso.saucelabs.com' in hosts file...
> INFO: 'maki76100.miso.saucelabs.com' is not in hosts file
> INFO: checking if maki77100.miso.saucelabs.com can be resolved
> INFO: resolving 'maki77100.miso.saucelabs.com' using default system settings...
> INFO: resolved to '162.222.77.100'
> INFO: resolving 'maki77100.miso.saucelabs.com' using DNS server '127.0.0.11'...
> INFO: resolved to '162.222.77.100'
> INFO: checking 'maki77100.miso.saucelabs.com' in hosts file...
> INFO: 'maki77100.miso.saucelabs.com' is not in hosts file
> INFO: checking if maki78100.miso.saucelabs.com can be resolved
> INFO: resolving 'maki78100.miso.saucelabs.com' using default system settings...
> INFO: resolved to '162.222.78.100'
> INFO: resolving 'maki78100.miso.saucelabs.com' using DNS server '127.0.0.11'...
> INFO: resolved to '162.222.78.100'
> INFO: checking 'maki78100.miso.saucelabs.com' in hosts file...
> INFO: 'maki78100.miso.saucelabs.com' is not in hosts file
> INFO: checking if connecting to Sauce Labs REST API via SSL works
> INFO: certificate #0 in chain: INFO: s:/OU=GT45345800/OU=See www.rapidssl.com/resources/cps (c)14/OU=Domain Control Validated - RapidSSL(R)/CN=*.saucelabs.com; INFO: i:/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3
> INFO: checking OCSP entry #0 (http://gv.symcd.com)
> INFO: resolving 'gv.symcd.com' using default system settings...
> INFO: resolved to '23.43.75.27'
> INFO: resolving 'gv.symcd.com' using DNS server '127.0.0.11'...
> INFO: resolved to '23.43.75.27'
> INFO: checking 'gv.symcd.com' in hosts file...
> INFO: 'gv.symcd.com' is not in hosts file
> INFO: URL http://gv.symcd.com can be reached
> INFO: checking CRL distribution point #0 (http://gv.symcb.com/gv.crl)
> INFO: resolving 'gv.symcb.com' using default system settings...
> INFO: resolved to '23.43.69.163'
> INFO: resolving 'gv.symcb.com' using DNS server '127.0.0.11'...
> INFO: resolved to '23.43.69.163'
> INFO: checking 'gv.symcb.com' in hosts file...
> INFO: 'gv.symcb.com' is not in hosts file
> INFO: URL http://gv.symcb.com/gv.crl can be reached
> INFO: certificate #1 in chain: INFO: s:/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3; INFO: i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
> INFO: checking OCSP entry #0 (http://g.symcd.com)
> INFO: resolving 'g.symcd.com' using default system settings...
> INFO: resolved to '23.43.75.27'
> INFO: resolving 'g.symcd.com' using DNS server '127.0.0.11'...
> INFO: resolved to '23.43.75.27'
> INFO: checking 'g.symcd.com' in hosts file...
> INFO: resolved to '23.55.155.27'
> WARNING: your hosts file contains an entry for 'g.symcd.com'.
> WARNING: only do this if instructed by Sauce Labs support.
> INFO: URL http://g.symcd.com can be reached
> INFO: checking CRL distribution point #0 (http://g.symcb.com/crls/gtglobal.crl)
> INFO: resolving 'g.symcb.com' using default system settings...
> INFO: resolved to '23.43.69.163'
> INFO: resolving 'g.symcb.com' using DNS server '127.0.0.11'...
> INFO: resolved to '23.43.69.163'
> INFO: checking 'g.symcb.com' in hosts file...
> INFO: 'g.symcb.com' is not in hosts file
> INFO: URL http://g.symcb.com/crls/gtglobal.crl can be reached
> INFO: checking if accessing https://saucelabs.com/rest/v1 works
> INFO: resolving 'saucelabs.com' using default system settings...
> INFO: resolved to '162.222.75.243'
> INFO: resolving 'saucelabs.com' using DNS server '127.0.0.11'...
> INFO: resolved to '162.222.75.243'
> INFO: checking 'saucelabs.com' in hosts file...
> INFO: resolved to '162.222.73.28'
> WARNING: your hosts file contains an entry for 'saucelabs.com'.
> WARNING: only do this if instructed by Sauce Labs support.
> ERROR: connecting to https://saucelabs.com/versions.json: Peer certificate cannot be authenticated with given CA certificates, reply: [empty].
> ERROR: can't reach https://saucelabs.com/versions.json, please check your firewall and proxy settings.
> INFO: checking if accessing http://google.com works
> INFO: resolving 'google.com' using default system settings...
> INFO: resolved to '216.58.213.174'
> INFO: resolving 'google.com' using DNS server '127.0.0.11'...
> INFO: resolved to '216.58.213.174'
> INFO: checking 'google.com' in hosts file...
> INFO: 'google.com' is not in hosts file
> INFO: URL http://google.com can be reached
> INFO: checking if accessing https://google.com works
> INFO: resolving 'google.com' using default system settings...
> INFO: resolved to '216.58.213.174'
> INFO: resolving 'google.com' using DNS server '127.0.0.11'...
> INFO: resolved to '216.58.213.174'
> INFO: checking 'google.com' in hosts file...
> INFO: 'google.com' is not in hosts file
> INFO: URL https://google.com can be reached

If I remove the saucelabs line in /etc/hosts, then saucelabs connect works fine. Is this line in /etc/hosts mandatory?

**Comment by elgalu** [comment]
Thanks @StephaneColson for figuring this out, you can send me a pull request with the fix by removing those lines at /etc/hosts

**Comment by StephaneColson** [comment]
OK will do. Was not sure of the issue, thanks for the confirmation.

**Comment by StephaneColson** [comment]
Done, build [Travis #396](https://travis-ci.org/elgalu/docker-selenium/builds/172019483) is OK. When do you plan to pull a new image in [Docker hub](https://hub.docker.com/r/elgalu/selenium/) ?

**Comment by elgalu** [comment]
Is ongoing:
https://travis-ci.org/elgalu/docker-selenium/jobs/180475940

**Comment by elgalu** [comment]
Released https://github.com/elgalu/docker-selenium/releases/tag/3.0.1j

**Comment by elgalu** [comment]
Should be fixed, can you re-test and close @StephaneColson ?

**Comment by StephaneColson** [comment]
Yes, it works now. Thanks!
