### ISSUE TITLE
Question - Chrome 55 Release

### ISSUE THREAD

**Issue by seangerhardt-wf** [elgalu/docker-selenium#138]
Hey Leo,

Any idea when we can expect a release that contains a chrome 55 image? 

As far as updating, is it as simple as updating the references of Chrome 54 to 55? If so, I'd be happy to put up a PR. 

I suspect we also have to push the image to docker hub, but couldn't understand from the contributing.md if that was handled by travis.ci automatically or not.

**Comment by elgalu** [comment]
I was planning to release next week but feel free to send a PR before that :)

The push is done automatically from Travis-CI for security and transparency, yes.

**Comment by seangerhardt-wf** [comment]
See https://github.com/elgalu/docker-selenium/pull/139
