### ISSUE TITLE
Position Firefox / Chrome Browser in upper top, left corner

### ISSUE THREAD

**Issue by valorize** [elgalu/docker-selenium#140]
Currently the window is positioned right next to seluser terminal window. Maybe 200pixel off from the window border. Is it possible to automatically reposition it to the top, left corner?

**Comment by elgalu** [comment]
Good catch! feel free to provide a PR else I may take a look in ~3 weeks. Thanks!

**Comment by valorize** [comment]
No rush. I got time *lol*. Which window manager is docker-selenium using?

**Comment by valorize** [comment]
Maybe this helps? http://unix.stackexchange.com/questions/48984/how-can-i-set-the-position-that-terminal-opens-at
