### ISSUE TITLE
Not able to run multiple tests in parallel 

### ISSUE THREAD

**Issue by mmraghavendra** [elgalu/docker-selenium#141]
Seeing below error when trying to run below command. Please suggest solution for this.
Command
========
export SELENIUM_HUB_PORT=4444 VNC_FROM_PORT=40650 VNC_TO_PORT=40700 VIDEO=false
docker-compose -p grid scale mock=1 hub=1 chrome=3 firefox=3

Error
====
Creating and starting grid_mock_1 ...
←[33mWARNING←[0m: Service hub is trying to use reuse the network stack of anothe
r service that is not running.
←[1BCreating and starting grid_hub_1 ... e
←[1Bting and starting grid_hub_1 ... error
ERROR: for grid_hub_1  Cannot create container for service hub: network grid_def
ault not found
Creating and starting grid_chrome_1 ...
Creating and starting grid_chrome_2 ...
Creating and starting grid_chrome_3 ...
←[33mWARNING←[0m: Service hub is trying to use reuse the network stack of anothe
r service that is not running.
←[33mWARNING←[0m: Service hub is trying to use reuse the network stack of anothe
r service that is not running.
←[33mWARNING←[0m: Service hub is trying to use reuse the network stack of anothe
r service that is not running.
←[1BCreating and starting grid_firefox_1 ...
Creating and starting grid_firefox_2 ...
Creating and starting grid_firefox_3 ...
←[33mWARNING←[0m: Service hub is trying to use reuse the network stack of anothe
r service that is not running.
←[33mWARNING←[0m: Service hub is trying to use reuse the network stack of anothe
r service that is not running.
←[33mWARNING←[0m: Service hub is trying to use reuse the network stack of anothe
r service that is not running.
←[2Bting and starting grid_firefox_2 ... done

**Comment by elgalu** [comment]
Good catch, I think I'm missing the [depends_on](https://docs.docker.com/compose/compose-file/#/dependson) docker-compose configuration option to properly handle the [startup order](https://docs.docker.com/compose/startup-order/)

**Comment by elgalu** [comment]
FYI your use case seems appropiate for using the project @diemol and I are working on: [Zalenium](https://github.com/zalando/zalenium)

If you give it a try I suggest you go with the one-liner [docs here](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#starting-zalenium-with-docker-compose) instead of docker-compose though there is also an example for that too.
