### ISSUE TITLE
Chrome resizing smaller than 400 px width not possible

### ISSUE THREAD

**Issue by ireinhart** [elgalu/docker-selenium#145]
With the latest image the chrome browser can not be resize to a smaller width than 400 px. With the image before (3.1.0-p3) that was not a problem.

I there an option to get chrome smaller than 400 px? I need this for device testing with galen.

**Comment by diemol** [comment]
This should be related to the Chrome and Chromedriver update, as seen in the change log...

* Upgrade Chrome major from 56 to 57.0.2987.98
* Upgrade Chromedriver minor from 2.27 to 2.28

**Comment by elgalu** [comment]
I agree with @diemol , this might be realted to Chrome `57.0.2987.98` or, less likely, Selenium 3.2.

I'm releasing in ~1hr https://github.com/elgalu/docker-selenium/releases/tag/3.2.0-p1 with Chrome `57.0.2987.110` let's see if they fixed the problem there.

**Comment by elgalu** [comment]
Hi @ireinhart, with @diemol, we [implemented](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#screen-resolution) the `screenResolution` Selenium capability:

```java
desiredCapabilities.setCapability("screenResolution", "200x200");
```

So by using [Zalenium](https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#install-and-start), which in turns uses this project, you should be able to achieve this.

This is working fine for me, with low resolutions:

![image](https://cloud.githubusercontent.com/assets/111569/24200183/947add3c-0f0c-11e7-8b4c-59066a52d2b5.png)

200x200 in this example, with Chrome:

![image](https://cloud.githubusercontent.com/assets/111569/24200217/b681d386-0f0c-11e7-900d-a59441e42b56.png)

**Comment by elgalu** [comment]
Ah, with Zalenium you can see it right away with the Live Preview feature:

![image](https://cloud.githubusercontent.com/assets/111569/24200564/c18eedc6-0f0d-11e7-89ba-96c8a4ecdc4f.png)

**Comment by ireinhart** [comment]
Thanks for your help. The latest image don't resolve my issue. I am using selenium 2.

We can't use zalenium with your selenium image, because we use kubernetes and I can not mount the docker socket into the zalenium image. That is not a good practice for clustering - I think.

**Comment by elgalu** [comment]
I'm sorry to hear that @ireinhart , I guess you will have to stick to version `3.1.0-p3` unless you find a way to fix this in which case a PR is more than welcome.

**Comment by diemol** [comment]
@ireinhart maybe you need to check if the latest Chrome version works well with Selenium 2.

Perhaps you could migrate one single test to use Selenium 3 and try again? It should work since we have tested it here, but with Selenium 3.

**Comment by elgalu** [comment]
@ireinhart not sure what's peculiar about your environment but given this is working good in our tests while using Zalenium I'll close this, please re-open if you still have this issue with latest release with Selenium 3.3.1
