### ISSUE TITLE
Add scene detection, drop desktop-only beginning of video(s)

### ISSUE THREAD

**Issue by AronNovak** [elgalu/docker-selenium#146]
ffmpeg has the ability to do scene-detection:
http://stackoverflow.com/questions/35675529/using-ffmpeg-how-to-do-a-scene-change-detection-with-timecode/38205105#38205105

My recent experience with the awesome video recording was that I had a hard time to spot the time point when the browser launches (5m+ video, 3-10 seconds of worthwhile content in it).
With the scene fllter of ffmpeg, I was able to handle the situation manually.

As I use docker-compose and the test is in the other container, so i do not have the ability to start the video on-demand. If we'd throw away the part of the video where nothing happens (optionally, via an environment variable), it would be quite helpful.

**Comment by AronNovak** [comment]
All our efforts for our use-case is documented at https://github.com/Gizra/drupal-elm-starter/pull/68

**Comment by diemol** [comment]
I understand what you mean, when just using docker-selenium it is quite complicated to have a video with the actual test content.

If you feel like, try [Zalenium](https://github.com/zalando/zalenium), we developed it with @elgalu and it is based on docker-selenium. 

In Zalenium we start the video recording when the session starts and stop the recording when the session is stopped or the test has been idle for a while.

**Comment by elgalu** [comment]
That's right, as with @diemol we are focusing more on Zalenium and this feature is already there I don't intend to also maintain it here so hope you guys can switch to Zalenium and start enjoying that any many other features like live preview, the local dashboard.html and so on.

**Comment by elgalu** [comment]
@AronNovak you can switch to Zalenium with docker-compose by taking a look at the example at https://github.com/zalando/zalenium/blob/master/docs/docker-compose.yaml

**Comment by AronNovak** [comment]
Thanks a lot for the suggestion, we created an issue for that:
https://github.com/Gizra/drupal-elm-starter/issues/83

It seems to be a drop-in replacement, so we're glad to switch to that and have strong video recording capabilities.
