### ISSUE TITLE
Opera Browser support

### ISSUE THREAD

**Issue by konfilios** [elgalu/docker-selenium#151]
Thanks for the great work. I was wondering if you're planning to support the Opera browser. It looks like there's a quite recent release of the OperaChromiumDriver which I guess works similarly to ChromeDriver https://github.com/operasoftware/operachromiumdriver/releases/tag/v.2.27

I would be glad to contribute if you have some guidelines on how to add support (and tests) for a new browser.

**Comment by elgalu** [comment]
Thanks @konfilios 

Do you know how much space would Opera add to the image? I might be ok with less than 100mb.

You would need to add the Opera browser installation to the Dockerfile.

For the tests I suppose some python tests would be enough, tests than don't require internet access would be even better, e.g. you could open the selenium grid console and perform some checks there.

I would suggest avoid using this:
https://github.com/operasoftware/operachromiumdriver/tree/master/examples

As those examples are 3 years old.

For python, tests should work with both python 2 and python 3 if possible, else just with python 3.

thanks!!

**Comment by elgalu** [comment]
No one showed interest in contributing to this and neither +1 reactions so I assume this is not strongly needed by the community. Closing for now. If someone really need this please send a PR with the addition along with a short explanation on how to keep it up to date, if there is a subscription channel to get Opera updates notifications even better so the upgrades can be automated.
