### ISSUE TITLE
NoSuchSessionException

### ISSUE THREAD

**Issue by khalistan** [elgalu/docker-selenium#155]

**Comment by elgalu** [comment]
Hi, can you share the whole docker run command you are using?

**Comment by khalistan** [comment]
docker run -d --name jenkins-slave empiriecom/jenkins-slave -master "http://192.168.38.129:8080" -username "Admin" -password "hmand" -executors "20" -name "localhost" -labels "webtest" -deleteExistingClients

**Comment by elgalu** [comment]
And the docker-run of docker-selenium?

**Comment by khalistan** [comment]
FROM jenkinsci/jenkins

USER root

RUN apt-get update \
	&& curl -sL https://deb.nodesource.com/setup_7.x | bash - \
	&& apt-get install -y wget expect nodejs locales xvfb dbus 	\
	&& npm install -g backstopjs

#============================================
# Google Chrome
#============================================
# can specify versions by CHROME_VERSION;
#  e.g. google-chrome-stable=53.0.2785.101-1
#       google-chrome-beta=53.0.2785.92-1
#       google-chrome-unstable=54.0.2840.14-1
#       latest (equivalent to google-chrome-stable)
#       google-chrome-beta  (pull latest beta)
#============================================
ARG CHROME_VERSION="google-chrome-stable"
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
  && apt-get update -qqy \
  && apt-get -qqy install \
    ${CHROME_VERSION:-google-chrome-stable} \
  && rm /etc/apt/sources.list.d/google-chrome.list \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

#==================
# Chrome webdriver
#==================
ARG CHROME_DRIVER_VERSION=2.29
RUN wget --no-verbose -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip \
  && rm -rf /opt/selenium/chromedriver \
  && unzip /tmp/chromedriver_linux64.zip -d /opt/selenium \
  && rm /tmp/chromedriver_linux64.zip \
  && mv /opt/selenium/chromedriver /opt/selenium/chromedriver-$CHROME_DRIVER_VERSION \
  && chmod 755 /opt/selenium/chromedriver-$CHROME_DRIVER_VERSION \
  && ln -fs /opt/selenium/chromedriver-$CHROME_DRIVER_VERSION /usr/bin/chromedrive


RUN rm -rf /var/lib/apt/lists/* /var/cache/

USER jenkins

**Comment by elgalu** [comment]
But you are not using this project, you seem to be building your own docker-selenium image

**Comment by elgalu** [comment]
Please open issues in this repository only if you use this project: docker run .. elgalu/selenium ...
