### ISSUE TITLE
wait_all_done failing in some cases

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#156]
The `wait_all_done` script failing in some cases, the logs aren't provided enough info as of now.

The problem seems related to `wait-selenium-node-chrome.sh` and also happens with Firefox.

**Comment by elgalu** [comment]
Apparently the xterm process fails at some point and kills the rest

```sh
docker exec -ti zalenium_40002 cat /var/log/cont/selenium-node-chrome-stdout.log | grep -i Trapped
-- INFO: Trapped SIGTERM/SIGINT on Chrome NODE
```

**Comment by elgalu** [comment]
Apparently this is a deadlock situation in Zalenium DockerSeleniumStarterRemoteProxy

**Comment by diemol** [comment]
It seems like that, therefore let's close this one.
