### ISSUE TITLE
Cross referencing video frames, tests logs, selenium logs, all logs

### ISSUE THREAD

**Issue by borisivan** [elgalu/docker-selenium#157]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

Probably outside of the scope of this project, but I figure I'll ask anyway. :)

The videos are excellent. Our tests yield tons of log messages, and cross referencing what we're seeing in the video, vs the log messages generated by the tests, can be difficult at times. I'd love to have the option of displaying a log message on the video recording. Maybe in a short modular window that stays in the foreground at bottom of screen, even if it's only capable of showing one log message at a time (keep overwriting for each new message) would be great.

I suppose it would probably need to be functionality that is listening on a port on the container.. but wow I'd love to send log messages and see them underneath the browser, in the video. It would really give the person watching the video all the context they're looking for, re: cross referencing where the test is, when cross referencing the animation with a large set of log messages that are stored elsewhere...

And of course, a way for Zalenium to tie in to it.

**Comment by elgalu** [comment]
> I'll ask anyway. :)

@borisivan I love feedback and feature ideas!!

### Cross referencing video with tests vs the logs
I thought about this also. In an ideal world I want to cross reference:

- tests logs
- video frames
- selenium grid logs
- selenium node logs
- browser driver logs
- browser console logs
- test screen shots
- container or OS relevant logs

Please someone correct me if I'm wrong but I think not even Saucelabs / BrowserStack have this feature.

Putting the logs in the video itself doesn't sound optimal to me, I would rather solve this Zalenium side, by using the timestamps of each log event we could potentially use ffmpeg to cut off the video frames in which each event log fits and show it in Zalenium dashboard.

Zalenium doesn't yet integrate the tests logs, this would also require some major change.

But you are in the right track I believe, to make UI testing great we need this!

**Comment by elgalu** [comment]
Some steps to allow cross referencing video frames with failed tests are in place in [3.5.3-p6](https://github.com/elgalu/docker-selenium/releases/tag/3.5.3-p6)

From Zalenium, after a test being marked as failed, is now possible to:

```sh
docker exec some_chrome_or_firefox_container notify "TEST FAILED"
```

This message notification will appear inside the container looking like this:

![image](https://user-images.githubusercontent.com/111569/30786681-407a36aa-a17a-11e7-81fc-80aefa492300.png)

This means that the video will have recorded the moment in which the test failed.

**Comment by borisivan** [comment]
That is great and has tons of potential! For example, let's say my test has important state changes that I'm logging. When a test fails, the triage effort is typically cross referencing the video with the log, looking at them side by side trying to 'merge' the two in my head.

If it would be possible to let the user define the size and location of the notify, that allows us to address most of the points raised in the comments above. For example, let's say I started the browser such that it was for the most part full screen, minus the bottom 10% of the screen. And then if my notify consumed the remainder (i.e. that bottom 10% of the screen..), then if I did something like this: (I'm just guessing at the values here for now):

docker exec some_chrome_or_firefox_container notify -startx 0 -starty 1000 -width 1920 -height 80 $logMsg

... then that allows those particular log messages to be displayed right in the video, neatly under the browser.

**Comment by diemol** [comment]
I was checking the package installed for the notifications, and it does not allow to customise starting position neither size. Check https://ss64.com/bash/notify-send.html

We'll add the notifications as they are from Zalenium when a test fails and on demand.

I would say that on the docker-selenium side, there is no more to do, if someone wants to have the notifications, he/she should implement the command calls in their scripts.
