### ISSUE TITLE
Cert Support, Add Ability to Mount Arbitrary Folders in Node File System

### ISSUE THREAD

**Issue by ReservedDeveloper** [elgalu/docker-selenium#158]
This is an auxiliary in relation to zalando/zalenium#148.

Currently trying to add client certificate support to the nodes spun up by Zalenium via this library. However, as the directory (`/home/seluser/.pki/nssdb/`) doesn't exist in the base image for this project, there's no mount point to hook in to.

Would love to have that directory added to the image (perhaps with a flag to override certs), or the ability to create directories via a flag (perhaps by way of `DefaultDockerContainer#copyToClient`).

The current workaround is to pull the latest image for `elgalu/selenium`, add the directory, and commit the changes to a local image. Workable, but not ideal.

**Comment by elgalu** [comment]
@ReservedDeveloper can you send me a PR? this seems like simply doing `mkdir -p /home/seluser/.pki/nssdb/` in the Dockerfile. If I understood correctly.

**Comment by elgalu** [comment]
This repository already allows to mount arbitrary folders as is run via docker run.

So you just need to docker run ... -v /home/seluser/.pki/nssdb:./nssdb for example.

If I'm correct then this issue only makes sense to have it open at Zalenium project.

**Comment by ReservedDeveloper** [comment]
You're absolutely right. I should have looked more closely at the internals there. Sorry about that!
