### ISSUE TITLE
Issue similar to https://github.com/SeleniumHQ/selenium/issues/3808

### ISSUE THREAD

**Issue by sachs7** [elgalu/docker-selenium#166]
Any workaround available?

Docker version 17.06.0-ce, build 02c1d87
docker-compose version 1.14.0, build c7bdf9e
Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

========================================================================================= test session starts =========================================================================================
platform darwin -- Python 3.6.0, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
cachedir: .cache
sensitiveurl: .*
metadata: {'Python': '3.6.0', 'Platform': 'Darwin-16.6.0-x86_64-i386-64bit', 'Packages': {'pytest': '3.1.3', 'py': '1.4.34', 'pluggy': '0.4.0'}, 'Plugins': {'variables': '1.6.1', 'splinter': '1.8.5', 'selenium': '1.11.0', 'metadata': '1.5.0', 'html': '1.15.1', 'base-url': '1.4.1'}, 'Base URL': '', 'Driver': None, 'Capabilities': {}}
rootdir: 
plugins: variables-1.6.1, splinter-1.8.5, selenium-1.11.0, metadata-1.5.0, html-1.15.1, base-url-1.4.1
collected 0 items / 1 errors 

=============================================================================================== ERRORS ================================================================================================
______________________________________________________________________________ ERROR collecting tests/test_home_page.py _______________________________________________________________________________

E   selenium.common.exceptions.WebDriverException: Message: None
E   Stacktrace:
E       at java.util.HashMap.putMapEntries (HashMap.java:500)
E       at java.util.HashMap.putAll (HashMap.java:784)
E       at org.openqa.selenium.remote.DesiredCapabilities.<init> (DesiredCapabilities.java:54)
E       at org.openqa.grid.web.servlet.handler.RequestHandler.process (RequestHandler.java:104)
E       at org.openqa.grid.web.servlet.DriverServlet.process (DriverServlet.java:83)
E       at org.openqa.grid.web.servlet.DriverServlet.doPost (DriverServlet.java:67)
E       at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)
E       at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
E       at org.seleniumhq.jetty9.servlet.ServletHolder.handle (ServletHolder.java:841)
E       at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle (ServletHandler.java:543)
E       at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:188)
E       at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle (SessionHandler.java:1584)
E       at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:188)
E       at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle (ContextHandler.java:1228)
E       at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:168)
E       at org.seleniumhq.jetty9.servlet.ServletHandler.doScope (ServletHandler.java:481)
E       at org.seleniumhq.jetty9.server.session.SessionHandler.doScope (SessionHandler.java:1553)
E       at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope (ScopedHandler.java:166)
E       at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope (ContextHandler.java:1130)
E       at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
E       at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle (HandlerWrapper.java:132)
E       at org.seleniumhq.jetty9.server.Server.handle (Server.java:564)
E       at org.seleniumhq.jetty9.server.HttpChannel.handle (HttpChannel.java:320)
E       at org.seleniumhq.jetty9.server.HttpConnection.onFillable (HttpConnection.java:251)
E       at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:279)
E       at org.seleniumhq.jetty9.io.FillInterest.fillable (FillInterest.java:112)
E       at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run (ChannelEndPoint.java:124)
E       at org.seleniumhq.jetty9.util.thread.Invocable.invokePreferred (Invocable.java:122)
E       at org.seleniumhq.jetty9.util.thread.strategy.ExecutingExecutionStrategy.invoke (ExecutingExecutionStrategy.java:58)
E       at org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume.produceConsume (ExecuteProduceConsume.java:201)
E       at org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:133)
E       at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:672)
E       at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run (QueuedThreadPool.java:590)
E       at java.lang.Thread.run (Thread.java:748)

Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

- [ ] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`

- [ ] If I don't have latest version of docker I will specify which version with `docker --version` output

#### Docker-Compose
_(if using docker-compose)_

- [x] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

- [ ] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output

**Comment by elgalu** [comment]
I understand your pain, that issue 3808 is so annoying.

Try to force 'selenium': '3.3.1' on your requirements.txt, your output shows version '1.11.0'

**Comment by sachs7** [comment]
It is a pytest plugin: pytest-selenium v1.11.0
Installed Selenium version is 3.4.3

Tried docker image for selenium grid 3.3.1 but no luck!

**Comment by sachs7** [comment]
Update: In my local system, selenium was 3.4.x, downgraded it to 3.3.1 and works now with docker-selenium:3.3.1

**Comment by elgalu** [comment]
yep that's what I meant

So we can close this?

**Comment by sachs7** [comment]
Yes, please. Thanks.
