### ISSUE TITLE
Browser dies often, unsure how to upgrade chromedriver

### ISSUE THREAD

**Issue by dprski33** [elgalu/docker-selenium#170]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`
> Linux ip-10-234-30-58 4.9.32-15.41.amzn1.x86_64 #1 SMP Thu Jun 22 06:20:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

> [jenkins@ip-10-234-30-58 ~]$ docker pull elgalu/selenium
> Using default tag: latest
> latest: Pulling from elgalu/selenium
> Digest: sha256:074a221077f1948d173ddb0d1da0ca58c188ceadc4c69b9f7029d7c4b55497ef
> Status: Image is up to date for elgalu/selenium:latest

- [ ] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [ ] I have latest version of docker and I will specify here the output of `docker --version`

> Docker version 17.03.1-ce, build 7392c3b/17.03.1-ce

- [ ] If I don't have latest version of docker I will specify which version with `docker --version` output

My builds hit this error quite often causing the test run to fail:
> no such session
>   (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.9.32-15.41.amzn1.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 2 milliseconds
> Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
> System info: host: '931c80cf478d', ip: '172.18.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.32-15.41.amzn1.x86_64', java.version: '1.8.0_111'
> Driver info: org.openqa.selenium.chrome.ChromeDriver
> Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e), userDataDir=/tmp/.org.chromium.Chromium.euUlLJ}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=55.0.2883.87, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
> Session ID: 35654461df9da0ff4d1629454d9a06ff
> Command duration or timeout: 160 milliseconds
> Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
> System info: host: 'dda524c4615b', ip: '172.18.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.32-15.41.amzn1.x86_64', java.version: '1.7.0_111'
> Session ID: 210fad2b-f70c-4e70-8e55-4e2388f94aab
> Driver info: org.openqa.selenium.remote.RemoteWebDriver
> Capabilities [{platform=LINUX, javascriptEnabled=true, acceptSslCerts=true, browserName=chrome, chrome={userDataDir=/tmp/.org.chromium.Chromium.euUlLJ, chromedriverVersion=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e)}, networkConnectionEnabled=false, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, webdriver.remote.sessionid=210fad2b-f70c-4e70-8e55-4e2388f94aab, pageLoadStrategy=normal, version=55.0.2883.87, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=true, applicationCacheEnabled=false, takesScreenshot=true}]

I was hoping to upgrade the chromedriver version to attempt to fix this but I don't know how.
> Driver info: chromedriver=2.25.426924

**Comment by elgalu** [comment]
My image has chromedriver 2.31 so you are not actually using it, just pulling it

**Comment by elgalu** [comment]
Perhaps this can help you: https://stackoverflow.com/questions/45793360/why-does-chromedriver-2-31-fail-to-start-when-run-in-docker

I'll close for now as I haven't heard any feedback in 1 week.

**Comment by dprski33** [comment]
Someone who used to work with me was trying to solve a problem by forking this repo:
https://github.com/elgalu/docker-selenium/compare/master...outerpasta:master

It doesn't appear that the stackoverflow you linked to is related; can you tell what problem outerpasta was trying to solve?

I've since then switched back to this project instead of the outerpasta fork, updated to a newer version of chromedriver and have seen no problems.

Lastly, what does this project offer that the official Selenium one doesn't?

Thanks.

**Comment by elgalu** [comment]
Where exactly did you update chromedriver? in your host machine?

This image has chromedriver 2.31 and you report in your logs 2.25.426924 , as I wrote before you are not using the image, you can pull the image, even run it, but if your tests don't point to the container selenium server it won't work.

outerpasta's fork is from 2016, there are many unmaintained forks.

This project offers video recording, when comparing to the official one.

This project works better when being used from Zalenium:
https://github.com/zalando/zalenium

You will have a dashboard of the executed tests, it's pretty cool. Maybe you can give Zalenium a try. Try to launch it with the one-liner:

```
curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | bash -s start -i
```
