### ISSUE TITLE
Is there an idle timeout so that video doesn't consume disk?

### ISSUE THREAD

**Issue by borisivan** [elgalu/docker-selenium#171]
I came across a video file that was 25G. It couldn't been from an active tests, and my testNG timeout aborts any test if it runs for more than 5 minutes. It was likely from a test suite that aborted ungracefully, and did not issue the command to stop the video, or stop the docker container, etc.

Somehow, the container remained running, and the browser still active within that container, recording video. I do vaguely recall looking to see what containers were still present yesterday and saw one that shouldn't be there, so I stopped and deleted it (but hadn't thought to look if video was recording). Only stumbled across the video today:

-rw-r--r-- 1 root root **32120615554** Aug 28 19:45 vid_chrome_25550_firefox_25551.mkv

Difficult to say if there is a bug in elgalu/selenium or not. This was a Jenkins -> Maven -> Surefire -> testNG process that I think I aborted. Whether or not the TCP connection for the remoteWebDriver went away and the selenium hub didn't notice it, or if it was still maintained in the background and therefore selenium (and your video recording) were happily running along for days, but in any case, it looks like it can occur, regardless of how we got there.

I think this really needs an idle timeout of some kind, even if it;'s not a default value. If I specify an idle timeout of <x> seconds, then if there are no Selenium commands from the test in that amount of time, the video should stop, and the session end. I think a similar concept was introduced in Zalenium, but I think it's needed here to in elgalu/selenium.

Some version info:

The elgalu/selenium container would have been whatever was latest as of 8/22/2017, or newer. I automatically pull latest before each test suite.

Linux xxxx 3.12.39-47-default #1 SMP Thu Mar 26 13:21:16 UTC 2015 (a901594) x86_64 x86_64 x86_64 GNU/Linux

Docker version 17.04.0-ce, build 78d1802

**Comment by elgalu** [comment]
Hi, thanks for the detailed report.

This image doesn't know when a test ends so video recording continues as long as the container is alive or unless you execute `docker exec grid_container_name stop-video` as explained at https://github.com/elgalu/docker-selenium/blob/master/docs/videos.md#stop

However you might be better switching to [Zalenium](https://github.com/zalando/zalenium) as it correctly handles this particular issue among many other features, please take a look. Zalenium uses this image internally.

**Comment by borisivan** [comment]
Thanks for the response. For what it's worth, I did try zalenium ~3-4 months ago, and may try it again. At the time there were some performance/stability issues that were being worked on.

For the elgalu/selenium image, when running the suite, I create the container, and do a video start -> stop for every test, copy the video file, and stop the container at suite end.

But if the suite crashes and the container is left open, we can't risk the disk being consumed, I really think that adding that functionality here is needed.

**Comment by elgalu** [comment]
The functionality is already added to Zalenium so we don't intend to add it in this image but you figure out how to solve it here please send a PR.

**Comment by borisivan** [comment]
re: looking at doing a PR, if I instantiate a RemoteWebDriver in my test, and my test suite crashes before doing a stop video or stopping the docker container, I'm assuming that the selenium hub loses a TCP connection that was being used for the RemoteWebDriver and the browser closes, is that correct? I should have tried looking at the 25G video to see if the browser went away. I'm assuming/hoping it did.

If so, maybe I could add an option (non default) in which:

with parameter -e "stopVideoOnNoBrowser=true"

* if video is running
* examine every 10 seconds to see if there is a browser running
* if I can conclude there are no browsers running for 3 10 second iterations (or make that configurable, but don't want to over complicate this...)
* then stop video

I think making such a parameter non default would be good, because some might start your container with video on by default, and not get around to launching their first browser until a bunch of setup occurs, and are used to this working today. I start the container with video off, and only start it when I'm ready for it, but I'm sure not everyone does that.

... would something like that work? Want to make sure there isn't a reason why this wouldn't be a good idea.

**Comment by elgalu** [comment]
> examine every 10 seconds to see if there is a browser running

We definitely don't want to include a long running watcher process like this inside the container. It should be a clean solution, not this kind of hack. 

At this point it might be better if you give Zalenium another try and report back ;)

**Comment by diemol** [comment]
@borisivan 
Yeah, months ago we had performance issues with Zalenium, we worked on them and it is behaving much better now. 
If you had time, I would be interested in your feedback, thanks!
