### ISSUE TITLE
Override Chrome UserAgent in Docker Compose

### ISSUE THREAD

**Issue by WillGibson** [elgalu/docker-selenium#172]
Is it possible to override the UserAgent string in the Docker Compose YAML?

#### Docker-Compose
➜ docker-compose -v
docker-compose version 1.14.0, build c7bdf9e

**Comment by elgalu** [comment]
override? what's the current value? can you point me into the line code?

**Comment by WillGibson** [comment]
@elgalu I was hoping to be able to slip something into it using something like "general. useragent. override" in http://kb.mozillazine.org/Firefox_:_FAQs_:_About:config_Entries#General..2A.

Not sure it's possible?

The original reason for wanting to do it has gone away since I wrote that (change of tack), but I would still be interested to know if it's possible with elgalu/docker-selenium for future reference.

**Comment by elgalu** [comment]
Ah I get it now, @diemol wrote a guide, check https://github.com/zalando/zalenium/issues/176#issuecomment-313132398

Also, it might be better if you use Zalenium, it has more features than this project.

**Comment by WillGibson** [comment]
Thanks @elgalu
