### ISSUE TITLE
host.docker can't be reached in version 3.5.3

### ISSUE THREAD

**Issue by victorMerlis** [elgalu/docker-selenium#177]
#### Operating System
- Linux vic 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
#### Image version
- 3.5.3
#### Docker version
- 17.03.1-ce
![screenshot from 2017-09-24 17-11-52](https://user-images.githubusercontent.com/29833162/30783852-85b49576-a152-11e7-89ac-b860dd773a49.png)

**Comment by elgalu** [comment]
Can you try `docker.for.mac.localhost` instead of `host.docker` ?

**Comment by elgalu** [comment]
It seems we need docker 17.06 or above to try this out https://stackoverflow.com/a/43541732/511069

**Comment by diemol** [comment]
`docker.for.mac.localhost` does not work in Chrome, that's why in Zalenium this was implemented:
https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md#accessing-the-host

**Comment by elgalu** [comment]
@victorMerlis please pull again, should be [fixed no](https://github.com/elgalu/docker-selenium/releases/tag/3.5.3-p5) -- Indeed I introduced this bug recently while fixing a `sudo` issue for Kubernetes. This time I added some tests so it doesn't break again ;)

**Comment by elgalu** [comment]
No feedback yet, please re-open if is still an issue ;)
