### ISSUE TITLE
"Selenium failed me for the last time" error

### ISSUE THREAD

**Issue by amitaibu** [elgalu/docker-selenium#18]
When invoking the command from the README
```
docker run --rm --name=ch -p=0.0.0.0:8081:8484 -p=0.0.0.0:2222:2222 \
                          -p=0.0.0.0:4470:4444 -p=0.0.0.0:5920:5900 \
    -e SCREEN_WIDTH=1800 -e SCREEN_HEIGHT=1110 \
    -e VNC_PASSWORD=hola -e WITH_GUACAMOLE=true \
    -e SSH_PUB_KEY="$(cat ~/.ssh/id_rsa.pub)" \
    elgalu/selenium:v2.45.0-ssh2
```

I get `Selenium failed me for the last time` every time. The first time I've ran the command I actually got same error but for the tomcat server.

Running on mac.

**Comment by elgalu** [comment]
Are you connecting selenium to port 4470 or 4444? Watch the port bindings
in the docker run line.

Did you try to browse into localhost:8081 to see the browser to determine
your page is visible? User is *docker* password *hola* for the guacamole
server.

Note that localhost within the docker container is not the same as your
host machine so you need to figure out you network config. If you are new
to docker there a few things to consider.

Also the error "selenium failed for the last time" is too generic. Paste
the whole trace if the issue is still there after checking out the
statements above.

**Comment by amitaibu** [comment]
> Are you connecting selenium to port 4470 or 4444? Watch the port bindings
in the docker run line.

I was just copy / pasting the example from the README :)  Should it be `4444` all the way?

**Comment by amitaibu** [comment]
Anyway, also with 4444 I get the errors. [Here's](https://gist.github.com/amitaibu/9ccf58de55c32aaf3b9a) the log

**Comment by amitaibu** [comment]
Oh, and just to answer your questions:

> Did you try to browse into localhost:8081

Tried, but it's not working since Docker never finished to run.

> Note that localhost within the docker container is not the same as your
host machine so you need to figure out you network config

Yeah, I'm using `boot2docker ip` to get it on my Mac.

**Comment by elgalu** [comment]
Thanks for the info! Can you try to run it with `WITH_GUACAMOLE=false` note that it should end without failures and with a message similar to this:

```
Container docker internal IP: 172.17.1.76
start.sh all done and ready for testing
```

idk why you're getting `listen6: bind: Address already in use` after `INFO - Launching a standalone server` is there something already running on port 4444?

**Comment by amitaibu** [comment]
Sure, I'll check it when I'm back home. On my office computer it's working, but I get another error -- I'll open another issue :)

**Comment by amitaibu** [comment]
So back in my office computer which worked once, I now get the same error (even after restart). I've confirmed that nothing already listens to those ports (`lsof -i :4444 && lsof -i :5590`), but still selenium can't connect ([log](https://gist.github.com/amitaibu/0e503b888ff0d7ee3aa0))

**Comment by amitaibu** [comment]
(btw, also made sure no other docker instance is running)

**Comment by elgalu** [comment]
Confirmed: http://stackoverflow.com/q/26021181/511069
Will push a fix soon.

**Comment by elgalu** [comment]
Pushing **v2.45.0-oracle1** please retry with image `elgalu/selenium:v2.45.0-oracle1` in about 30mins ;)

**Comment by elgalu** [comment]
Pushed please try again with version `v2.45.0-oracle1`

**Comment by amitaibu** [comment]
Thanks, but I don't see it in the tags list 

![elgalu_docker-selenium_repository___docker_hub_registry_-_repositories_of_docker_images](https://cloud.githubusercontent.com/assets/125707/8010984/970f72dc-0bbd-11e5-9083-06a99c4cea4c.jpg)

```
Unable to find image 'elgalu/selenium:v2.45.0-oracle1' locally
Pulling repository elgalu/selenium
FATA[0010] Get https://index.docker.io/v1/repositories/elgalu/selenium/images: dial tcp: lookup index.docker.io on 62.219.186.7:53: read udp 62.219.186.7:53: i/o timeout 
```

**Comment by elgalu** [comment]
Sorry I fixed the link, should now be:
https://registry.hub.docker.com/u/elgalu/selenium/tags/manage/

**Comment by amitaibu** [comment]
Seems to be working :) :+1:
