### ISSUE TITLE
Connection error 403

### ISSUE THREAD

**Issue by amitaibu** [elgalu/docker-selenium#19]
I assume this is a support question, since the docker is running fine and I'm able to connect to Guacamole - on Mac I use `boot2docker ip` to get the IP and then for example `http://192.168.59.103:8081/#/` is available.

However, when I try to connect to `http://192.168.59.103:4470/` I get 

![error_403_forbidden_for_proxy_and_skype-3](https://cloud.githubusercontent.com/assets/125707/7908397/3ba8402c-084d-11e5-8c19-37a99cb8e1d3.jpg)

Command used is the one from the README:

```
docker run --rm --name=ch -p=0.0.0.0:8081:8484 -p=0.0.0.0:2222:2222 \
                          -p=0.0.0.0:4470:4444 -p=0.0.0.0:5920:5900 \
    -e SCREEN_WIDTH=1800 -e SCREEN_HEIGHT=1110 \
    -e VNC_PASSWORD=hola -e WITH_GUACAMOLE=true \
    -e SSH_PUB_KEY="$(cat ~/.ssh/id_rsa.pub)" \
    elgalu/selenium:v2.45.0-ssh2
```

**Comment by elgalu** [comment]
4470 is the port for selenium, not for guacamole, so the correct url is: **192.168.59.103:4470/wd/hub** i.e. path is `/wd/hub` not `/#/` for selenium

**Comment by amitaibu** [comment]
:+1: 

I'll create a PR to improve the README for suckers like me :)

**Comment by elgalu** [comment]
hehe np! README updated: https://github.com/elgalu/docker-selenium/commit/70d2319489d4572dde9323aac71f917dcb15e100

**Comment by amitaibu** [comment]
Great, thanks! :)
