### ISSUE TITLE
How to add extension to chrome

### ISSUE THREAD

**Issue by BjornMelgaard** [elgalu/docker-selenium#193]
Suppose I have crx file of [`Node.js V8 --inspector Manager`](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj) downloaded from chrome store via [Get CRX extension](https://chrome.google.com/webstore/detail/get-crx/dijpllakibenlejkbajahncialkbdkjc) 

[link](https://ufile.io/lubgt)

and I want to use chrome in docker with this extension preinstalled, how can I do this?

[related issue](https://github.com/SeleniumHQ/docker-selenium/issues/343) in `SeleniumHQ/docker-selenium`, hadnt tested it

#### Operating System
- [x] `Linux machine 4.9.63 #1-NixOS SMP Sat Nov 18 10:22:25 UTC 2017 x86_64 GNU/Linux`

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`

Docker version 17.09.0-ce, build afdb6d44a80f777069885a9ee0e0f86cf841b1bb

#### Docker-Compose
_(if using docker-compose)_

- [x] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

docker-compose version 1.15.0, build e12f3b9

**Comment by elgalu** [comment]
I've never tried this. Maybe the community can help you. If you figure it out you can write the findings here;)

**Comment by thekiiingbob** [comment]
@BjornMelgaard For me, I set the extensions in the chromeOptions object. I use Webdriver.io (Node.js), so that entry looks like
```
chromeOptions: {
    ...
    extensions: [fs.readFileSync("./myExtension.crx", "base64")]
    ...
}
```

I had various issues originally using the extension, but found out you had to base64 encode to the options like this.

More info here - https://sites.google.com/a/chromium.org/chromedriver/capabilities

**Comment by BjornMelgaard** [comment]
@thekiiingbob much thanks

I'll better close it since others have no issues with using chrome extensions
