### ISSUE TITLE
Dropdowns are not working in docker

### ISSUE THREAD

**Issue by srghma** [elgalu/docker-selenium#194]
How to reproduce:
go here - https://jsfiddle.net/9dr1wvdk/4/

Then hover and click on link
I able to do this in my system chrome, but not in chrome in docker session

#### Operating System
- [x] `Linux machine 4.9.63 #1-NixOS SMP Sat Nov 18 10:22:25 UTC 2017 x86_64 GNU/Linux`

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`

Docker version 17.09.0-ce, build afdb6d44a80f777069885a9ee0e0f86cf841b1bb

#### Docker-Compose
_(if using docker-compose)_

- [x] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

docker-compose version 1.15.0, build e12f3b9

**Comment by elgalu** [comment]
@BjornMelgaard it's been a while, did you figure this out?

**Comment by diemol** [comment]
@srghma 
Could you please provide a Selenium script that can be used to reproduce the issue? Just using plain Selenium official bindings.

**Comment by srghma** [comment]
@diemol I was using capybara + rspec

I can't provide the capybara script, but it's straitforward to make one

**Comment by diemol** [comment]
@srghma ok, looking forward to the script, please post it here when you have it. Thanks.

**Comment by diemol** [comment]
Also, please be aware that we don't use Ruby for our tests, so it would be great to have specific instructions showing how to execute the script you will provide.

**Comment by srghma** [comment]
@diemol I dont have script

you can try to reproduce it using only selenium commands

```
visit page
click dropdown
expected(page).to have_dropdown_open
```

**Comment by diemol** [comment]
Sorry @srghma, but without a reproduction scenario/script, it is very unlikely that we will have a look at it and this will likely be closed since we don't have a way to reproduce it. 

This is also done that way to avoid any bias on out way to reproduce a scenario, we could be using a different type of selectors or page load strategy for example.

**Comment by srghma** [comment]
I'll reopen if I have script
