### ISSUE TITLE
chrome not running with specified device (mobile emulation mode)

### ISSUE THREAD

**Issue by hubidu** [elgalu/docker-selenium#196]
When running tests in mobile emulation mode, chrome does not apply the correct device settings (specified by device name). It works with version 3.7.1 of the image

I am using the following chrome options

```
chromeOptions: {
  deviceName: 'iPhone 6'
}
```
When I look at the video of the tests I can see that chrome does not apply width/height of the device

#### Operating System
- Linux veve-dev-test-01 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Image version
- I have latest version of this image 3.8.1-p0

#### Docker version
- Docker version 17.04.0-ce, build 4845c56

#### Docker-Compose
- docker-compose version 1.16.1, build 6d1ac21

**Comment by diemol** [comment]
Hi @hubidu,

I am not 100% sure if something changed towards this specific setting. What I see in the reference [page](https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation) is that they don't sent the deviceName as a key value pair inside the chromeOptions array. The example shows that a `mobileEmulation` array needs to be placed inside the chromeOptions one. E.g. (taken from the page):

```java
Map<String, String> mobileEmulation = new HashMap<>();
mobileEmulation.put("deviceName", "Nexus 5");

ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.setExperimentalOption("mobileEmulation", mobileEmulation);
WebDriver driver = new ChromeDriver(chromeOptions);
```

Can you please double check that?

**Comment by hubidu** [comment]
Tried again today with 3.8.1-p3 . Still same problem.

Although of not much help for troubleshooting, I attached a screenshot of one of our UI tests. The screenshot should show the tablet version of gmail, but you can see it shows the mobile version (albeit in tablet width). So obviously gmail thinks  it's dealing with a mobile phone and not a tablet.

When I go back to 3.7.1 everything works as intended, i. e. Gmail correctly detects an iPad and uses a two column layout.

As for the chrome options: 

Sorry, but I don't understand. Where do you take it from that chromeOptions and/or mobileEmulation should be an array? As far as I can see the code you gave is the Java equivalent of 

chromeOptions: {
  deviceName: 'Nexus 5'
}


![mtuxmzi0mza4ms4zmtmlmjatjtiwss5zzwuosgvyciuymfbly3ulmjbjbmzvcm1hdglvbiuymhp1jtiwswhyzxilmjbbbmzyywdljtiwaw0lmjbdsevdszi0jtiwvmvyc2ljagvydw5nc2nlbnrlci52ai51aikucg5n](https://user-images.githubusercontent.com/13134082/33985202-3a01d876-e0ba-11e7-8d0b-1260d8816b67.png)

**Comment by diemol** [comment]
Hi @hubidu,

I took the example code from here:
https://sites.google.com/a/chromium.org/chromedriver/mobile-emulation

That is why asked if perhaps you need to change the code.

**Comment by vganapat** [comment]
I too see the same behavior when I use the latest version image of `docker-selenium` along with `webdriverio` in Jenkins CI. 

I've tried running tests with both `mobileEmulation` and variations of modifying the `user-agent`, to no avail (this works fine with 3.7.1 as @hubidu noted as well).  

``` 
capabilities: [
         {
             browserName: 'chrome',
             version: '*',
             chromeOptions: {
                 mobileEmulation: {
                     deviceName: 'iPhone 6 Plus'
                 }
             },
```

``` args: ['use-mobile-user-agent', 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1'] ```

```  args: [
                     'user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1'
                 ] ```

**Comment by mmedasani** [comment]
Hi @hubidu Did you find any solution to this problem? I am seeing the same issue

**Comment by mmedasani** [comment]
Thank you for your response @vganapat 
But it is already sending the chromeoptions as the goog:chromeoptions. 
It works locally but when running the tests on hub it does not emulate the mobile device. It used to work perfectly, not sure what changed but it has stopped working since nov/dec of 2017.

**Comment by mmedasani** [comment]
I was able to get the mobile emulation working by downgrading the selenium.webdriver version from 3.8 to 3.5.1.

**Comment by iMbaundso** [comment]
Hi all, hi @mmedasani , just a quick note... I also stumbled about this issue while updating from Zalenium 3.7.1i to 3.10.0a. After changing chromeOptions to "goog:chromeOptions" in our capabilities it worked fine. Maybe it's worth to try it again ;) Just one more note if it's still not working, we are using specific deviceMetrics instead of deviceNames.

```
capabilities: [
    {
        browserName: 'chrome',
        "goog:chromeOptions": {
             mobileEmulation: {
                 "deviceMetrics": {
                      "width": 360,
                       "height": 640,
                       "pixelRatio": 3
                  },
                  "userAgent": "Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19"
             }
       }
```

**Comment by elgalu** [comment]
Most people report that setting via `goog:chromeOptions` fixed the problem so will close this one.

**Comment by SantiagoPass** [comment]
Hi! I'm having the same error, when I execute the test cases, the same size screen is always displayed even when I change the device emulation.

I'm using the following code:

ChromeOptions chromeOptions = new ChromeOptions();
Map<String, String> mobileEmulation = new HashMap<>();
mobileEmulation.put("deviceName", "iPhone 5/SE");
chromeOptions.setExperimentalOption("mobileEmulation", mobileEmulation);
driver = new ChromeDriver(chromeOptions);

The following screen size is always displayed (using different deviceName):
![screenshoot automation](https://user-images.githubusercontent.com/43584372/69364135-86766d00-0c70-11ea-81a8-f9b00dc535c0.png)

The expected screen for the selected device is: 
![screenshoot without automation](https://user-images.githubusercontent.com/43584372/69364176-a017b480-0c70-11ea-9e37-9a206170a9f5.png)

**Comment by reddyinfo** [comment]
I too got like SantiagoPass commented on Nov 21, 2019

Is there any solution please
