### ISSUE TITLE
newbie question, how to use this to run cucumber features ?

### ISSUE THREAD

**Issue by mlotfi2005** [elgalu/docker-selenium#206]
Hi, 
I am new here, I started learning selenium cucumber, created features tests , I use ruby code, I am in Windows 7, I run the grid as you said 
docker pull elgalu/selenium
Then
 docker run -d --name=grid -p 4444:24444 -p 5900:25900  -e TZ="US/Pacific" -v /dev/shm:/dev/shm --privileged elgalu/selenium

I went to 
http://192.168.99.100:4444/grid/console

I can see two browsers (Firefox and Chrome).

How to test the files.feature in my project ?

Thanks, your help is appreciated.

**Comment by diemol** [comment]
Hi @mlotfi2005,

I am not familiar with Cucumber, but somehow you should be able to point your WebDriver tests to http://192.168.99.100:4444/grid/console in your config files, right?

**Comment by elgalu** [comment]
Closing as no updates were sent.
