### ISSUE TITLE
Sikuli integration request - help needed

### ISSUE THREAD

**Issue by shankarkc** [elgalu/docker-selenium#209]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
NA

#### Image version
NA

#### Docker version
NA

#### Docker-Compose
NA
- [ ] If I don't have latest version of docker-compose I will specify which version with `docker-compose 
NA

If we integrate [Sikuli](https://github.com/sterodium/selenium-grid-extensions/releases) with selenium grid It will become very powerful/useful addition to grid so that user can upload/download files from grid, Also can control keyborad of remote grid. In some cases only setFileDetector is not enough. Scenarios like when a page prompts username/pwd can be handled using sikuli. but setFileDetector cannot be used there.

Usage guide is available [here](https://github.com/sterodium/selenium-grid-extensions)
```
 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java  -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.33_64bit -Dwebdriver.gecko.driver=/tmp/webdriver/geckodriver/geckodriver_0.19.1 -cp /opt/selenium_ex/SeleniumGridExtras-jar-with-dependencies.jar:./all-node-extensions.jar:./extension-proxy.jar:/tmp/webdriver/3.8.1.jar org.openqa.grid.selenium.GridLauncherV3 -role node -nodeConfig node_5555.json -log log/node_5555.log
```

You can use  download the binaries from https://github.com/sterodium/selenium-grid-extensions/releases and add it to grid launch command prompt as above.
I can create the pull request. But I am not sure where to add this code. we need to 
 * download the Sikuli binaries
 * Add sikuli jars to class path before launching selenium grid
Please help me to identify the right location for this change.

**Comment by elgalu** [comment]
Hi, I think Sikuli is way out of the scope of this project. So unless someone wants to work on this and send a PR I will close this for now.
