### ISSUE TITLE
How do I change display resolution?

### ISSUE THREAD

**Issue by felippenardi** [elgalu/docker-selenium#21]
I wanted to set an specifc resolution size of the display for a better VNC usage. Is there a setting for that?

**Comment by elgalu** [comment]
Is right there in the README, `SCREEN_WIDTH` and `SCREEN_HEIGHT` https://github.com/elgalu/docker-selenium#non-privileged

**Comment by elgalu** [comment]
You mean you want to scale up/down while connecting with VNC? `-e SCREEN_WIDTH=2000` sets the screen width at 2000 pixels for example.

**Comment by felippenardi** [comment]
Thank you, sorry for missing it!
