### ISSUE TITLE
Unable to downgrade the gecko version and build image

### ISSUE THREAD

**Issue by barahate90** [elgalu/docker-selenium#210]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
Linux awsdlb1.xyz.com 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
#### Image version
cloned the project from 
https://github.com/elgalu/docker-selenium.git
#### Docker version
Docker version 1.12.6, build ec8512b/1.12.6
#### Docker-Compose
NO

Trying to downgrade the gecko-driver version in this file in my local 
" https://github.com/elgalu/docker-selenium/blob/master/Dockerfile"

After changing the file version  i am using this command to build image " docker build -t selenium ."

every time I am trying to build the image it is getting failed . please check the attached screen shot .
![docker-error](https://user-images.githubusercontent.com/3815898/35729117-b086cafe-07db-11e8-8746-7ad13b0b3dad.PNG)

**Comment by elgalu** [comment]
Docker version 1.12.6 is too old, please upgrade.

**Comment by barahate90** [comment]
Small update on this issue .

Yes we need latest docker version so that while building docker image it should build properly. 
but the issue i have mentioed here is related to network . I have resolved this by building my image with open network and pushing to my docker hub repository .
