### ISSUE TITLE
FEATURE REQUEST - How can a custom browser configuration be included ?

### ISSUE THREAD

**Issue by b3ster** [elgalu/docker-selenium#217]
The Problem is that we need to include certificats and other settings which can not be passed in a exeptable way via remote driver.
Could you please point me into the correct direction where to inlcude that ?

Thank you very much :)

**Comment by verhuja** [comment]
I was able to achieve this for firefox:

- Created a firefox profile more or less the same way as it is explained [here](https://github.com/SeleniumHQ/docker-selenium/wiki/How-to-use-a-Firefox-custom-profile)
- Install your certificates in the firefox profile
- In the docker-compose.yml added environment: - JAVA_OPTS=-Dwebdriver.firefox.profile=selenium

**Comment by diemol** [comment]
Hi @b3ster,

Yes, as @verhuja says, you could either build your own Chrome/Firefox profiles and use them within your tests. Or build a custom docker-selenium image with the certificates already installed in it.

I'll close this issue since it is more a question than a real issue.
