### ISSUE TITLE
New image versions are not present at docker hub 

### ISSUE THREAD

**Issue by elxroman** [elgalu/docker-selenium#227]
https://hub.docker.com/r/elgalu/selenium/tags/

```
docker pull elgalu/selenium
```
will return 3.11.0-p1 as latest

```
$ docker pull elgalu/selenium:3.11.0-p3
Error response from daemon: manifest for elgalu/selenium:3.11.0-p3 not found
```

**Comment by elgalu** [comment]
Hi @elxroman thanks for reporting, we will try to fix it soon.

**Comment by elgalu** [comment]
Should be fixed now: https://hub.docker.com/r/elgalu/selenium/tags/

**Comment by elxroman** [comment]
Looks OK now! Thanks!
