### ISSUE TITLE
Docker-compose with VNC viewer-Connection closed unexpectedly.

### ISSUE THREAD

**Issue by SatishD1** [elgalu/docker-selenium#230]
Hi All,

   I have build a docker compose file for running selenium script. when i start the docker-compose file i get the Ports exposed but am not able to connect to the ports using VNC viewer. `docker-compose version 1.18.0, build 8dd22a96`

Can you please help me here. Here is my docker compose file

![image](https://user-images.githubusercontent.com/34995213/37823872-d874a12a-2eb0-11e8-9b90-93cd2ff4316a.png)

When i do `docker-compose up -d` the containers are created and ports are exposed as below.
![image](https://user-images.githubusercontent.com/34995213/37824006-4f14e506-2eb1-11e8-8c3c-7cfb589b925a.png)

When i try to connect to the machine '127.0.0.1:32774' or '127.0.0.1:32775' using VNC viewer it says as below.
![image](https://user-images.githubusercontent.com/34995213/37824083-852f6bf2-2eb1-11e8-9fee-b6e44f18b58e.png)

**Comment by elgalu** [comment]
Hi @SatishD1 you are referring to a different project, please open the issue there:
https://github.com/SeleniumHQ/docker-selenium

Or, if you want to see the tests running plus having a nice dashboard with all the videos of the tests and many other features I suggest you use Zalenium:
https://github.com/zalando/zalenium

To start it you just need 1 line:
```
curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | bash -s start -i
```

Then check the dashboard at http://localhost:4444/dashboard/
