### ISSUE TITLE
Hub and Nodes on Different Instances with Latest Images of Hub and Chrome

### ISSUE THREAD

**Issue by saifsysim** [elgalu/docker-selenium#231]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [Linux RHEL ] I provided my operating system name and version, e.g. output of `uname -a`

#### Image version

Hub Version v.3.11.0
Chrom Node : v:65.0.3325.181

I am trying top run Chrome containers in a different instance and Hub in a diff instance 

Hub start command : 

> docker run -d -p 4444:4444 --name selenium-hub hub:v1

ChromeNode on a diff Host : 

> docker run -d -p 5454:5555 -e REMOTE_HOST=http://$HOSTNAME:5454 -e HUB_PORT_4444_TCP_ADDR=10.XXX.XXX.XXX -e HUB_PORT_4444_TCP_PORT=4444 --name chrome-node100 selenium-chrome-node:1.0.0

This used to work for me sometime back, since I updated the latest Hub and chrome images this isnt working.
Is there a change in Hub host and port commands ????`

**Comment by elgalu** [comment]
`selenium-hub` is a different project, this is `elgalu/selenium`
