### ISSUE TITLE
How to deploy on Amazon BeanStalk

### ISSUE THREAD

**Issue by amitaibu** [elgalu/docker-selenium#25]
This is obviously an optimistic support question :)

I was wondering if you have experience in deploying to Amazon BeanStalk using a `Dockerrun.aws.json` file?

I'm writing a blog post about using this docker image to level up testing (headless Chrome instead of PhantomJs), and I'd be happy to give an easy solution for deploying.

**Comment by elgalu** [comment]
No experience with BeanStalk but looks promising, please share your post link here when is ready! :)

**Comment by amitaibu** [comment]
will do, I currently do it on DigitalOcean, I'll open an issue with more info there. Closing this for now.

**Comment by saadqc** [comment]
@amitaibu Did you write the blog? If yes, kindly share the link it would help

**Comment by amitaibu** [comment]
No, I'm using DigitalOcean.
