### ISSUE TITLE
Set default pixel format for ffmpeg to YUV420P?

### ISSUE THREAD

**Issue by TobiX** [elgalu/docker-selenium#256]
Currently, the default settings for ffmpeg are:

https://github.com/elgalu/docker-selenium/blob/cb7d4e25357fa69b72e56097d299e2516615c759/Dockerfile#L934

Since `x11grab` creates frames with full color depth, this generates H.264 streams with the YUV444P pixel format. This is unfortunate, since the OpenH264 decoder used in Firefox doesn't support that pixel format (AFAICS). Would it be possible to add `-pix_fmt yuv420p` to the default options?

**Comment by elgalu** [comment]
Sure @TobiX , just send us a PR
