### ISSUE TITLE
Firefox seems to ignore no proxy settings for Java based test

### ISSUE THREAD

**Issue by remeltucker** [elgalu/docker-selenium#261]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`
Linux
#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

- [ ] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [ ] I have latest version of docker and I will specify here the output of `docker --version`

- [x] If I don't have latest version of docker I will specify which version with `docker --version` output
17.05.0-ce
#### Docker-Compose
_(if using docker-compose)_

- [ ] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

- [x] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output
1.21.0
Gave ENV params in the docker file for proxy and no proxy. When running Java based tests on Firefox, the website pops up the proxy dialog. Does not do that for a Python test. No issues at all in chrome.
Is this any known issue? Tried this on the latest image and also on 3.7.0 p1 since that is what we were using . We are running tests using Zalenium and elgalu/selenium

**Comment by remeltucker** [comment]
Can you please specify what info you are looking for so that I can provide you that. Apologize for providing incomplete info

**Comment by elgalu** [comment]
Hi, a few things, how do you docker run, with what parameters or which docker compose file, how do you the tests, with what capabilites, what test fails and with which output, also you wrote `seems to ignore` so you are not sure? . Once you provide all the info maybe someone from the comunity will be able to help.

**Comment by remeltucker** [comment]
Docker Compose file as shown below 
Usage:
#   docker-compose up --force-recreate
version: '3'
services:
 zalenium:
   image: dosel/zalenium:latest
   container_name: zalenium
   hostname: zalenium
   tty: true
   restart: always
   volumes:
     - /dev/xvdf:/dev/xvdf
     - /usr/bin/docker:/usr/bin/docker
     - /zalenium:/home/seluser/videos
     - /var/run/docker.sock:/var/run/docker.sock
   ports:
     - 4444:4444
     - 8080:4444
   privileged: true
   command: >
    start --desiredContainers 1
          --maxTestSessions 2
          --maxDockerSeleniumContainers 10
          --timeZone "America/New_York"
          --videoRecordingEnabled true
          --sendAnonymousUsageInfo false
          --seleniumImageName "elgalu/selenium:latest"
   environment:
          - zalenium_http_proxy=http://<proxyurl>:<port number>/
          - zalenium_https_proxy=https://<proxyurl>:<port number>/
          - zalenium_no_proxy=127.0.0.1,localhost,<list of urls>

As far as I have observed, firefox brings up the proxy pop up when running selenium tests written in java whereas it is fine on python and that is why I mentioned as "seems to ignore".

Test fails with unhandled alert because of the proxy dialog

Note: I also tried giving the proxy by customizing the elgalu/selenium docker file and giving the ENV parameters.

In all these cases, chrome works fine

**Comment by remeltucker** [comment]
I have raised a geckodriver issue for this (https://github.com/mozilla/geckodriver/issues/1365).
Can close this issue here.
