### ISSUE TITLE
Video is not viewable in QuickTime

### ISSUE THREAD

**Issue by micheletest** [elgalu/docker-selenium#263]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`
`Darwin BNY210.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64`
`Mac OSX High Sierra 10.13.5`

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`
`INFO: Docker Img. Version: 3.13.0-269`

I'm running zalenium with the video feature on. The mp4s created are not able to be opened in Mac QuickTime. There error is: `The document “zalenium_better_com_selenium_chrome_LINUX_20180731192830987_COMPLETED.mp4” could not be opened. The file isn’t compatible with QuickTime Player.`

I'm wondering if there is a way around this issue? Maybe I need to pass a different CODEC to the container.

A workaround is to drag/open the video in chrome, it plays fine there.

Thanks.

**Comment by elgalu** [comment]
Hi! maybe @TobiX has some hint? He is our Video encoding expert after #258 :)

**Comment by micheletest** [comment]
Yes, I was wondering if he would have some idea. I am not familiar at all with video encoding, and what little I read indicates that the recent change he made should have helped.

**Comment by TobiX** [comment]
I'm not really sure where to start. Do you have "ffprobe" handy? (I think you can get it by installing ffmpeg  via Homebrew)

Try

    ffprobe -v quiet -print_format json -show_format -show_streams  video.mkv

and look for something suspicious (maybe compare with a similar, playable file). You can also post it here and I'll take a look.

**Comment by diemol** [comment]
Pushed a fix, will be released soon
