### ISSUE TITLE
Chrome browser image ignoring DNS server IP

### ISSUE THREAD

**Issue by zeevMetz** [elgalu/docker-selenium#269]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`

#### Image version
- [ ] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

- [x] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`

- [ ] If I don't have latest version of docker I will specify which version with `docker --version` output

#### Docker-Compose
_(if using docker-compose)_

- [ ] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

- [ ] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output

The latest version "3.14.0-p3" of the selenium image causes the Chrome browser to ignore the DNS server IP that we set in /etc/resolv.config file, once the container is running. This issue is not occuring with Firefox, either with the previous image "3.14.0-p2"

Thanks,

Operating system: Linux
Image version: 3.14.0-p2
Docker version: 18.03.1-ce

**Comment by diemol** [comment]
@zeevMetz 
Bare in mind that the only difference between 3.14.0-p2 and 3.14.0-p3 is the Chrome version, so I would imagine that it is a Chrome issue more than a docker-selenium one.

Have you tried to reproduce the issue with a local Chrome?
If it is an issue happening only with docker-selenium, how can we reproduce it?

**Comment by zeevMetz** [comment]
@diemol 
Hi, sorry for the long delay.
Yes, I tried to reproduce it on a local Chrome with DNS Server IP and it worked regularly.
You can reproduce it, when a container runs you can change to the DNS Server IP, and you'll see that Chrome ignoring it and pointing to the world.

**Comment by diemol** [comment]
Could you please give us detailed steps on how to reproduce it?

**Comment by zeevMetz** [comment]
Hi, 

Forgot to mention that I'm using dosel/zalenium 3.11.0h to run with selenium grid infrastructure.

Steps to reproduce:

1. Start a test with Selenium WebDriver
2. Use Zalenium to run a container(elgalu/selenium:3.14.0-p2 with Chrome node) 
3. When the container is running change DNS Server IP (/etc/resolv.conf) of the running container.

**Comment by zeevMetz** [comment]
@diemol  
Are the detailed steps satisfying?

**Comment by diemol** [comment]
How is this "When the container is running change DNS Server IP (/etc/resolv.conf) of the running container." exactly done?

Can you give us an example with detailed steps? Not just phrases but also specific values that we can use to reproduce it.

In addition, why is that configuration changed on runtime? Can it be done before?

**Comment by diemol** [comment]
Closing as we didn't any more replies.
