### ISSUE TITLE
Implement logrotate and config value to MAX log size

### ISSUE THREAD

**Issue by amitaibu** [elgalu/docker-selenium#27]
I've [setup](https://gist.github.com/amitaibu/fe2e3579ce138283c94e) a demo server on Digital ocean, and I using `glances` I've noticed the docker container was gradually getting bigger.

Here's the command I use:

```
docker run -d --name=ch \
  -p=0.0.0.0:8484:8484 -p=0.0.0.0:2222:2222 \
  -p=0.0.0.0:4470:4444 -p=0.0.0.0:5920:5900 \
  -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1080 \
  -e VNC_PASSWORD=gizra -e WITH_GUACAMOLE=false \
  elgalu/selenium:v2.46.0-base1
```

Some memory stats:
![docker-stop](https://cloud.githubusercontent.com/assets/125707/8167852/9a444f38-13a9-11e5-8bef-f41b105bee2b.jpg)

Docker stopped: 120mb
Docker started, no test ran: 210mb

After 1st test: 240mb
After 2nd test: 285mb
After 3rd test: 305MB

It might be related to logs being accumulated? If so, maybe we can have a switch for that.
My goal is having a server running this container as deamon, so my devs can use it on their local/ Travis to test.

@elgalu if you want I can send you the credentials to the server -- it's a sandbox.

**Comment by elgalu** [comment]
I would create a new container on each test run disposing the used
containers.
Please send me a PR if you figure out what's causing the grow ;)

**Comment by amitaibu** [comment]
> I would create a new container on each test run disposing the used
containers.

fair enough, it's what I'm doing for Shoov. 

I was hoping to get it to work for my Travis, but I guess I can hook a simple nodejs that will run a new docker.

**Comment by elgalu** [comment]
Changed the issue name to "Implement logrotate and config value to MAX log size" and reopening so I remind myself to do this.

**Comment by elgalu** [comment]
Fixed in https://github.com/elgalu/docker-selenium/releases/tag/v2.46.0-sup but warning: there are breaking changes so read the docs again or test the image first before pushing it directly into your CI.
