### ISSUE TITLE
Install adblock

### ISSUE THREAD

**Issue by d4rqu** [elgalu/docker-selenium#271]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

- [ ] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`

- [ ] If I don't have latest version of docker I will specify which version with `docker --version` output

#### Docker-Compose
_(if using docker-compose)_

- [x] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

- [ ] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output

**Comment by diemol** [comment]
Hi @d4rqu,

Please check how to install Chrome extensions via ChromeDriver. 
http://chromedriver.chromium.org/extensions

Php is out of the scope of this project. You would need to build your own custom image with it.
