### ISSUE TITLE
Problem Chrome prompt Download Host Ubuntu 16.04.5 LTS

### ISSUE THREAD

**Issue by evandromartines** [elgalu/docker-selenium#272]
When I run the latest version of the image running on Mac with the settings below Chrome successfully ignores Download Prompt:
		chromePrefs.put("profile.default_content_settings.popups", 0);
		chromePrefs.put("downloadPath", pathDirDownload);
		chromePrefs.put("behavior",  "allow");
		
		chromePrefs.put("download.default_directory", pathDirDownload);
		chromePrefs.put("download.directory_upgrade", true);
		chromePrefs.put("download.prompt_for_download", false);
		
		chromePrefs.put("safebrowsing.enabled", false);
		chromePrefs.put("plugins.plugins_disabled", new String[]{"Chrome PDF Viewer"});
		
		chromePrefs.put("credentials_enable_service",false);
		chromePrefs.put("profile.password_manager_enabled",false);
		chromePrefs.put("plugins.always_open_pdf_externally",true);

But when I run the same image and with the same settings using Ubuntu 16.04.5 LTS host above the chrome ignores the configuration and displays the download prompt.

regards

**Comment by diemol** [comment]
Hi @evandromartines,

Can you please fill the complete template in a new issue? We need to see how you start the container and what versions of docker you use.

**Comment by evandromartines** [comment]
Hi diemol, 

I found the problem, in the assembly of the volume inside the container needed permission in the folder, so the download prompt appeared.
