### ISSUE TITLE
Record a selenium session

### ISSUE THREAD

**Issue by amitaibu** [elgalu/docker-selenium#29]
@elgalu another support question, wondering if you know

Shoov is integrated with docker-selenium (currently on DEV, but it works really nice!), and my next thought is video recording the session, a la sauce labs. Do you have any experience with such a thing, or can provide some pointers?

**Comment by elgalu** [comment]
Yes, video recording is in the roadmap, for know you can implement it yourself by reading https://github.com/elgalu/docker-selenium/issues/17#issuecomment-115564318

**Comment by elgalu** [comment]
Closing as duplicate of #17
