### ISSUE TITLE
There is a warning message when packaging with source code.

### ISSUE THREAD

**Issue by huotaihe** [elgalu/docker-selenium#293]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [ ] Linux GYB-T-SAS-07 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Source code version
- [ ] f8e1a8b
#### Docker version
- [ ] Docker version 18.09.0, build 4d60db4

## Warning info
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

**Comment by elgalu** [comment]
is just a warning ;)
