### ISSUE TITLE
FFMPEG_DRAW_MOUSE=0 has no effect

### ISSUE THREAD

**Issue by max-horvath** [elgalu/docker-selenium#297]
Hi,

#### Operating System
- [x] I provided my operating system name and version, e.g. output of `uname -a`
Darwin Kernel Version 18.2.0
macOS 10.14.2

#### Image version
- [x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

#### Docker version
- [x] I have latest version of docker and I will specify here the output of `docker --version`
Docker version 18.09.0, build 4d60db4

#### Problem
According to README.MD there are environment variables to customize video recording.

I wanted to simply record a test case _without_ the mouse cursor.

    FFMPEG_DRAW_MOUSE=0

Specifying this environment variable won't lead to success - the mouse cursor still appears on the recordings.

Cheers,
Max

**Comment by max-horvath** [comment]
#298 fixes the issue ...

**Comment by diemol** [comment]
Closing as #298 was merged and released.
