### ISSUE TITLE
Can not find tag for version 2.47.1m

### ISSUE THREAD

**Issue by david-nossebro** [elgalu/docker-selenium#307]
I am not able to find any tag for elgalu/selenium:2.47.1m, which exist on dockerhub. I want to use that version to test firefox version 38.0.6, but get some errors. I would like to see the code for whats running in the container.

**Comment by diemol** [comment]
@david-nossebro 
The tag is there, sometimes when there are too many tags, the GitHub UI does not show them:

```
git tag | grep 2.47                                                                                                                                                                                                                             ✔  14:39:09
2.47.1a
2.47.1b
2.47.1c
2.47.1d
2.47.1e
2.47.1f
2.47.1g
2.47.1h
2.47.1i
2.47.1j
2.47.1k
2.47.1l
**2.47.1m**
2.47.1n
```

https://github.com/elgalu/docker-selenium/releases/tag/2.47.1m

**Comment by david-nossebro** [comment]
Ahh, I did not know that. Thanks @diemol!
