### ISSUE TITLE
Command to change right on files

### ISSUE THREAD

**Issue by eravion** [elgalu/docker-selenium#313]
Hello,

Some commands to change right on files before trying to buil the image :
chmod 755 ./bin/chrome_stable_version
chmod 755 ./bin/firefox_version
chmod 755 ./utils/bin/generate_capabilities_json
chmod 644  GLOBAL_PATCH_LEVEL.txt

Thanks.

**Comment by diemol** [comment]
Hi @eravion, 
Feel free to create your own image by extending this one, and make changes in a way that suits your needs.

**Comment by eravion** [comment]
My goal was to inform that this repo is not working as it is, some updates have to be done.
I made it and I want to share.

**Comment by diemol** [comment]
If there is something not working properly, please share complete information and the error you get. There is a template when the issue is created
