### ISSUE TITLE
Add chmod in Dockerfile

### ISSUE THREAD

**Issue by eravion** [elgalu/docker-selenium#314]
Hello

I have to add this line in Dockerfile

RUN chmod -R 755 /opt/google/

Thanks.

**Comment by diemol** [comment]
Hi @eravion, 
Feel free to create your own image by extending this one, and make changes in a way that suits your needs.

**Comment by eravion** [comment]
My goal was to inform that this repo is not working as it is, some updates have to be done.
I made it and I want to share.

**Comment by diemol** [comment]
If there is something not working properly, please share complete information and the error you get. There is a template when the issue is created
