### ISSUE TITLE
question about the video recording

### ISSUE THREAD

**Issue by eravion** [elgalu/docker-selenium#315]
Hello,

I have a problem with the video :

seluser@bc155916c554:/$ cat /var/log/cont/video-rec-stdout.log
--LOG 10:46:29:205671701 Waiting for file /home/seluser/videos/vid_firefox_25551* to be created...
Waiting for ffmpeg video recording to start...
.ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, x11grab, from ':30.0':
  Duration: N/A, start: 1554972389.400732, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1300x999, 29.97 fps, 29.97 tbr, 1000k tbn, 29.97 tbc
.[libx264 @ 0xc21fe0] height not divisible by 2 (1300x999)
Output #0, matroska, to '/home/seluser/videos/vid_firefox_25551.mkv':
    Stream #0:0: Video: h264, none, q=2-31, 128 kb/s, 10 fps
    Metadata:
      encoder         : Lavc56.60.100 libx264
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Videos at /home/seluser/videos/vid_firefox_25551.mp4* started to be recorded! (wait-video-rec.sh)

Can you please help me to fix it ?

Thanks.

**Comment by eravion** [comment]
Answering to myself ...

The problem looks to be the resolution of 1300x999.
Using something standard like 1280x800 fixe the problem.

BTW, I have an additional question about video recording.
How does it works ?
It record from the docker startup to the docker shutdown.
Could it be possible to have docker running 25/7 and to start the video recording when a new test start and stop it once the test is finished ?

**Comment by diemol** [comment]
Did you check the docs? Please have a look at https://github.com/elgalu/docker-selenium/blob/master/docs/videos.md, also keep in mind that this is an issue reporter and not a help forum. You could use StackOverflow or the Gitter channel for that.
