### ISSUE TITLE
New 3.14.0-p23 image versions are not present at docker hub 

### ISSUE THREAD

**Issue by dimkin-eu** [elgalu/docker-selenium#318]
$ docker pull elgalu/selenium:3.14.0-p23
Error response from daemon: manifest for elgalu/selenium:3.14.0-p23 not found

https://hub.docker.com/r/elgalu/selenium/tags/ shows only p22

same as https://github.com/elgalu/docker-selenium/issues/227 ?

**Comment by diemol** [comment]
A little patience, Travis is in the process of pushing right now https://travis-ci.org/elgalu/docker-selenium/builds/523861591
