### ISSUE TITLE
How to record a video without compression ?

### ISSUE THREAD

**Issue by algakzru** [elgalu/docker-selenium#323]
How to record a video without compression ?

I have enough space in hard disk and limited CPU, so I don't want to waste CPU on video compression, I have a scheduled task on a separate machine that will handle video compression.

I tried `FFMPEG_CODEC_ARGS=copy` and `FFMPEG_CODEC_ARGS=`, but none of these work.

#### Operating System

Linux GDais00016 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

#### Image version

3.141.59-p13

#### Docker version

Docker version 18.09.1, build 4c52b90

**Comment by diemol** [comment]
Thanks for figuring it out and posting it as a comment @algakzru
