### ISSUE TITLE
"Cannot call non W3C standard command while in W3C mode" error with Zalenium using 3.141.59-p15

### ISSUE THREAD

**Issue by qlikbez** [elgalu/docker-selenium#326]
It was working with 3.141.59-p14 version but now it is not working  with 3.141.59-p15.
I'm using Zalenium, the error I got is "Cannot call non W3C standard command while in W3C mode"

`UnknownCommandError: unknown command: Cannot call non W3C standard command while in W3C mode
        at Object.throwDecodedError (C:\Development\elastic-system-test\node_modules\selenium-webdriver\lib\error.js:514:15)
        at parseHttpResponse (C:\Development\elastic-system-test\node_modules\selenium-webdriver\lib\http.js:519:13)
        at doSend.then.response (C:\Development\elastic-system-test\node_modules\selenium-webdriver\lib\http.js:441:30)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
`
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [ ] I provided my operating system name and version, e.g. output of `uname -a`

#### Image version
- [ x] I have latest version of this image. Upgrade with `docker pull elgalu/selenium`

- [ ] If I don't have latest version of this image and can't upgrade, I will specify which one I'm using.

#### Docker version
- [ ] I have latest version of docker and I will specify here the output of `docker --version`

- [ ] If I don't have latest version of docker I will specify which version with `docker --version` output

#### Docker-Compose
_(if using docker-compose)_

- [ ] I have latest version of docker-compose and I will specify here the output of `docker-compose --version`

- [ ] If I don't have latest version of docker-compose I will specify which version with `docker-compose --version` output

**Comment by diemol** [comment]
@qlikbez 
From ChromeDriver & Chrome 75 and up, it will default to W3C mode, see release notes:
https://chromedriver.storage.googleapis.com/75.0.3770.8/notes.txt

It means that all commands must be W3C complaint, if you still need time to update your test scripts, you can pass `w3c: false` inside the `goog:chromeOptions` block. Take into account that the flag will probably be removed in future ChromeDriver releases.
