### ISSUE TITLE
Issue in Latest Selenium image - 3.141.59-p15

### ISSUE THREAD

**Issue by hariharanravichandran** [elgalu/docker-selenium#330]
1. Clicking a button on ModalBox should open a new window. But, It is now launching two windows.

2. On clicking a button, an alert should be thrown. On accepting the alert, the success message should be displayed on the nextpage. But, success page is not loading after accepting alert. 
After doing the same action twice, success page is displayed.

#### Operating System
Windows 7 

#### Image version
Zalenium Image: dosel/zalenium:latest
Last Worked Version:elgalu/selenium:3.141.59-p14
Not working in Version: elgalu/selenium:3.141.59-p15

#### Docker version
1.13.1

#### Docker-Compose
"docker run --rm -d --name zalenium -p 4444:4444 -p 5555:5555 \\\n" +
                        "     -v /var/run/docker.sock:/var/run/docker.sock \\\n" +
                        "     -v /tmp:/tmp/node/home/seluser/Downloads \\\n" +
                        "     -v /tmp:/home/seluser/Downloads \\\n" +
                        "     -v /tmp:/tmp/node/tmp \\\n" +
                        "     --label zalenium_main \\\n" +
                        "     --privileged dosel/zalenium:$zalenium start --seleniumImageName elgalu/selenium:$selenium --desiredContainers 1 --maxDockerSeleniumContainers 1 --maxTestSessions 1 --videoRecordingEnabled false --timeZone \"Europe/Dublin\""

**Comment by diemol** [comment]
@hariharanravichandran how can we reproduce the issue? 
Can you please provide a [concise reproducible test case](http://sscce.org/), that includes the page required to execute the scenario (a sample page or a public site).

**Comment by diemol** [comment]
Closing as we didn't get any replies from the OP
