### ISSUE TITLE
Mouse drag very slow

### ISSUE THREAD

**Issue by ahaverdings** [elgalu/docker-selenium#332]
The mouse drag event got really slow with the newest selenium image.
Older version:
![dragdrop1](https://user-images.githubusercontent.com/4309928/61216144-ed0cdc80-a70c-11e9-8110-3527f26ebf26.gif)
Newest version
![dragdrop2](https://user-images.githubusercontent.com/4309928/61216163-f4cc8100-a70c-11e9-8ff1-1e1683df8b56.gif)

#### Operating System
- zalenium:3.141.59g

#### Version
- elgalu/selenium:latest
- chrome driver: 75.0.3770.100

#### Last working version
- elgalu/selenium:3.141.59-p12
- chrome driver: 74.0.3729.131

Code for moving the mouse (by 10px each tick) using Java:
`
    public static void performMovement(Point movement, Actions builder) {
        Point movementRemains = new Point(Math.abs(movement.x), Math.abs(movement.y));
        Point movementDirection = new Point(Integer.signum(movement.x), Integer.signum(movement.y));
        while (movementRemains.x > 0 || movementRemains.y > 0) {
            Point movementStep = new Point(
                    movementRemains.x > 10 ? 10 : movementRemains.x,
                    movementRemains.y > 10 ? 10 : movementRemains.y
            );
            builder.moveByOffset(
                    movementDirection.x * movementStep.x,
                    movementDirection.y * movementStep.y);
            movementRemains.x -= movementStep.x;
            movementRemains.y -= movementStep.y;
        }
    }
`

**Comment by diemol** [comment]
@ahaverdings this might be a bug in Chrome/ChromeDriver, not related to `elgalu/selenium` since this image is just packaging the browser in a container. 
Please submit Chrome/ChromeDriver issues to the Chromium team, either at https://bugs.chromium.org/p/chromium or https://bugs.chromium.org/p/chromedriver.
