### ISSUE TITLE
http://localhost:4444/wd/hub/session 500 error

### ISSUE THREAD

**Issue by summer1914** [elgalu/docker-selenium#334]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

#### Operating System
- [x] Darwin MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

#### Image version
- [x] use `docker-selenium/docker-compose-tests.yml`，with no modification

#### Docker version
- Docker version 18.09.2, build 6247962

#### Docker-Compose

- [x] docker-compose version 1.23.2, build 1110ad01

#### Error detail

![image](https://user-images.githubusercontent.com/13167083/61445595-3d3fa500-a980-11e9-96bd-23feb1cc05e4.png)

**Comment by diemol** [comment]
@summer1914 Seems you are bumping into the issue where Chrome 75 and above work in W3C mode bu default, this means that you need to use a recent WebDriver client in order to send the proper capabilities.
