### ISSUE TITLE
Include last N versions of Chrome

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#35]
Include last N versions of Chrome and make it configurable via env var which one to use.

**Comment by elgalu** [comment]
The problem with this is where to get the chrome.deb packages securely given Google doesn't want to keep the old versions publicly :/

**Comment by milotx** [comment]
Extremely difficult to find. This is what I use http://mirror.pcbeta.com/google/chrome/deb/pool/main/g/google-chrome-stable/

**Comment by elgalu** [comment]
The problem is how can we trust that pcbeta.com site? just finding chrome deb files to download is not enough, you could be installing a trojan horse.

**Comment by milotx** [comment]
100% agreed. The only other option I have found is to pull old code bases and make the packages from source. However, all Google puts out there is Chromium, and in that case, its not an official deb which makes test variability a problem. The search continues... :/

**Comment by elgalu** [comment]
Waiting for this docker feature: https://github.com/docker/docker/issues/16584

**Comment by seangerhardt-wf** [comment]
@elgalu It looks like this has been open for quite awhile. 

Do you think there's any change in the ability to get last N versions of Chrome? 

This would still be very useful since the updated releases often include newer versions of Selenium and Chromedriver that often have fixes, yet adoption of the latest web browser may not be high, so testing on older versions is still desirable.

**Comment by elgalu** [comment]
@seangerhardt-wf you could take a look at: https://github.com/SeleniumHQ/docker-selenium/pull/267#issuecomment-285298565 and report back

**Comment by elgalu** [comment]
Testing in older versions can be achieved by docker pulling a previous version of this image with the corresponding Chrome / Firefox version required, by manually searching at [releases](https://github.com/elgalu/docker-selenium/releases). So closing this one...

**Comment by seangerhardt-wf** [comment]
@elgalu If we manually pull an older release, we won't get the fixes introduced by newer versions of selenium and chrome driver. I'll see if I can find a way to fix that
