### ISSUE TITLE
Version 3.141.59-p30 not available in official docker hub

### ISSUE THREAD

**Issue by xMutaGenx** [elgalu/docker-selenium#361]
As title suggests, would like to upgrade :)

**Comment by xMutaGenx** [comment]
Perhaps due to travis build failing? https://travis-ci.org/elgalu/docker-selenium/builds/619672067?utm_source=github_status&utm_medium=notification

**Comment by elgalu** [comment]
Sorry folks! it seems there's been a breaking change in the way docker-compose was naming containers

before:
```
grid_firefox_2
```

now:
```
grid_firefox_2_3bfc695e7e55
```

I'll fix the build soon, thanks for your patience:)

**Comment by elgalu** [comment]
https://github.com/elgalu/docker-selenium/releases/tag/3.141.59-p30

**Comment by elgalu** [comment]
Hi all, I've added the [Sponsor](https://github.com/sponsors/elgalu) link for this project.

If you use this free work for your projects please consider donating even a minimum amount so that we feel appreciated and start putting more hours into maintenance and feature improvements, thanks<3
