### ISSUE TITLE
Raise condition: video-rec: ERROR (not running)

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#45]
Getting this error in Travis now
https://travis-ci.org/elgalu/selenium-test-dockerized/builds/82508894
https://travis-ci.org/elgalu/selenium-test/builds/82513678

> INFO exited: selenium-node-firefox (exit status 124; not expected)

**Comment by elgalu** [comment]
Current workaround is to pass `-e VIDEO=true` to docker run.
This might although be related to default `WAIT_TIMEOUT="5s"` but unsure.

**Comment by smarques** [comment]
I have been getting the same error randomly but annoyingly, passing -e VIDEO=true did not fix it.
Using -e WAIT_TIMEOUT="25s" and --privileged seems to have worked, but maybe it's just a coincidence :octocat:

**Comment by elgalu** [comment]
I increased `WAIT_TIMEOUT` from `5s` to `15s` in version [2.48.2c](https://github.com/elgalu/docker-selenium/releases/tag/2.48.2c) hope that helps.
