### ISSUE TITLE
Video Record

### ISSUE THREAD

**Issue by divyaanandan** [elgalu/docker-selenium#47]
I started hub in my local machine & nodes are started in remote machine. I would like to see the running cases videos. So I tried following command for video recording. But video not stored in my dir. 

docker run --rm --name=hub -p 4446:24444 -p 5930:25900 -v /dev/shm:/dev/shm -e VNC_PASSWORD=hola -e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1480 -e CHROME=false -e FIREFOX=false -e VIDEO=true -e FFMPEG_FRAME_RATE=25 -e VIDEO_FILE_NAME="test" -e VIDEO_FILE_EXTENSION=mkv -e FFMPEG_CODEC_ARGS="" elgalu/selenium:2.47.1n

Did I miss anything?

Please help me to record the video

Thanks in Advance,

**Comment by elgalu** [comment]
Added a step by step guide, please check https://github.com/elgalu/docker-selenium/blob/master/docs/videos.md

**Comment by divyaanandan** [comment]
Thanks for your response. I tried it myself video was recording :) . But one problem, Proxy is not set in browser. Am facing URL connection refused problem. 

I set proxy in my test code :. 

"String PROXY = "localhost:port";
	org.openqa.selenium.Proxy proxy = new org.openqa.selenium.Proxy();
	proxy.setHttpProxy(PROXY);	
	proxy.setFtpProxy(PROXY);
	FirefoxProfile profile = new ProfilesIni().getProfile("default");
    profile.setAcceptUntrustedCertificates(true);
   	DesiredCapabilities capability= new DesiredCapabilities();
	capability.setCapability(CapabilityType.PROXY, proxy);
	capability.setCapability(FirefoxDriver.PROFILE,profile);
	capability= DesiredCapabilities.firefox();
   capability.setBrowserName("firefox"); "

**Comment by elgalu** [comment]
Sorry that profile proxy settings are out of scope of this project, please kindly close this issue as the video recording was clarified ;)
