### ISSUE TITLE
Issue with elgalu video recording 

### ISSUE THREAD

**Issue by divyaanandan** [elgalu/docker-selenium#48]
I have tried video recording, the given URL(www.google.com) not loaded in browser.

Do I have to set any proxies ?

![screenshot from 2015-10-26 18 41 34](https://cloud.githubusercontent.com/assets/15153117/10729709/44bddda6-7c11-11e5-84bc-ff6b735cb07f.png)

**Comment by elgalu** [comment]
Sorry this repo is not the place to troubleshoot your network issues.
