### ISSUE TITLE
chrome standalone: when trying to maximize the window, no such session error is thrown

### ISSUE THREAD

**Issue by bitliner** [elgalu/docker-selenium#49]
I am running protractor test against chrome standalone webdriver docker container.

Every time it tries to maximize the browser window programmatically, it throws an error saying `no such session`.

What am I doing wrong?

**Comment by elgalu** [comment]
What docker image exactly are you running? can you paste the `docker pull` command you're using?

**Comment by bitliner** [comment]
I just run `selenium/standalone-chrome:2.48.2` and docker pull it automatically.

Do you need any other information?

**Comment by elgalu** [comment]
You're opening the issue in the wrong project as you're pulling: https://github.com/SeleniumHQ/docker-selenium

This repo is about `elgalu/selenium:2.48.2a`
https://github.com/elgalu/docker-selenium#screen-size

**Comment by bitliner** [comment]
Sorry, thanks
