### ISSUE TITLE
Is it possible to set a specific proxy for each grid-node?

### ISSUE THREAD

**Issue by PatrickHuetter** [elgalu/docker-selenium#52]
I'm doing some webcrawling with selenium (java) and phantomjs. I would like to switch to a headless chrome/chromium.

For each crawl i'm using a different proxy-server with a new phantomjs instance (created by webdriver). Now i ask myself, wether it's possible to change the crawling system to this docker container but also have the possibility to set a proxy for each crawl. I'm not familiar with selenium-grid yet. I think it's reusing existing browser-instances and than it's not possible to change the proxy i think. Maybe it's possible to get a new grid browser-instances by a command?

I would be glad to hear some tips or answers wether it's possible to create such an environment with this docker image.

**Comment by elgalu** [comment]
Did u google it? :P

http://stackoverflow.com/questions/2887978/webdriver-and-proxy-server-for-firefox
http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp#using-a-proxy
http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp#using-a-proxy

**Comment by elgalu** [comment]
Closing as stale issue
