### ISSUE TITLE
Remote machine Video Recording

### ISSUE THREAD

**Issue by divyaanandan** [elgalu/docker-selenium#53]
Hi,

I started grid with my host machine. Given nodes are my test machines. Video was recording. But unable to view the actions in video. It gets look screen only. 
 
Commands :- 
Gird (From my machine ) :- 

docker run --rm --name=grid -p 4446:24444 -p 5920:25900 -v /dev/shm:/dev/shm -e VNC_PASSWORD=hola -e VIDEO=true -e FIREFOX=false -v $(pwd)/videos:/videos elgalu/selenium:2.47.1a

Nodes (From test machines):-

docker run --rm --name=node  -p 25550:25550 -p 25551:25551  -e SELENIUM_HUB_HOST=MY_MACHINE_IP  -e SELENIUM_HUB_PORT=4446  -e SELENIUM_NODE_HOST=TEST_MACHINE_IP -e GRID=false -e CHROME=true -e FIREFOX=true  elgalu/selenium:2.47.1n

Here, I cant attached my video. So I shared my screenshot here.

![nodes](https://cloud.githubusercontent.com/assets/15153117/11736399/e026142e-9ff3-11e5-94ab-ac0c6c968c51.png)

Note: If I run hub & node in same m/c, video recording correctly.
 Please do the needful asap. 

Thanks in Advance, 
Divya A

**Comment by elgalu** [comment]
I notice you are using version `elgalu/selenium:2.47.1a` and `2.47.1n` and 2 different versions that don't match, I never tested that scenario, please use the same version and preferable [newest](https://github.com/elgalu/docker-selenium/releases) e.g. `2.48.2f` as a start to see if that helps with your issue.

If it doesn't then it might be network related, firewall, correct IPs and so on, particular networking issues are not really in the scope of this project. Here are the docs: https://github.com/elgalu/docker-selenium#hub try to take another look please.

**Comment by divyaanandan** [comment]
Thanks for your suggestions. We have tried with you idea, but it didn't worked out for us and also we tried to capture screen actions with "VNC Viewer" but browsers wasn't displayed it. 

Currently, we were taking screen shots of the each test case, with "Take ScreenShot" web-driver interface and its working for us without any issue. Please let us know if you have any other options .

**Comment by elgalu** [comment]
Closing as stale issue
