### ISSUE TITLE
Number of chrome containers at the same time

### ISSUE THREAD

**Issue by eyal919** [elgalu/docker-selenium#56]
Hi,
How many chrome containers can be up and running at the same time?
My framework can run up to 300 tests at the same time. Currently we are using 96 vms and each one running 4 chrome instances so the grid is working fine. But I want to move to docker and create container per test but i need to know the limitation..

I have strong server 56 CPUs, 256GB RAM, 1700GB HD.

What do you think? how many containers I can have at the same time?

Thanks for your great work...

**Comment by elgalu** [comment]
I don't know, please let us know your findings!

In general docker should be more efficient than VMs and my guess is that you can have as many as your hardware can sustain.

Docker supports [runtime constraints on resources](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources) which can give you similar control to limit hardware usage as virtual machine technology does.

**Comment by elgalu** [comment]
Closing as stale issue
