### ISSUE TITLE
Video record only the browser

### ISSUE THREAD

**Issue by amitaibu** [elgalu/docker-selenium#57]
Seems currently the entire desktop is being captured. Is it possible to record only the specific provisioned browser?

**Comment by elgalu** [comment]
No but what you can do is to adjust the [screen size](https://github.com/elgalu/docker-selenium#screen-size) via `-e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1480` so the desktop will have the size you expect in your test.

It might be possible to capture only the browser but is not in my use case, PRs are welcome though.

**Comment by amitaibu** [comment]
:+1:
