### ISSUE TITLE
Show how to use with with new docker compose 1.6

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#60]
https://blog.docker.com/2016/02/compose-1-6/

**Comment by pedrro** [comment]
It´s related with the PR #59 ?

**Comment by elgalu** [comment]
Yes is related but since the fork or branch was removed I couldn't merge&squash #59 
So docker-compose support is [in place now](https://github.com/elgalu/docker-selenium/blob/master/docs/docker-compose.md#compose)
