### ISSUE TITLE
Can I share a screen with a Selenium session using this container?

### ISSUE THREAD

**Issue by snoblenet** [elgalu/docker-selenium#68]
I want to run a headless browser on the server within my Rails app. I want so share that browser's session with a web page in my app that users access through an iFrame in another web page in my app.

So for example:

- If a user clicked on a button in that iFrame, then the headless browser would click on the corresponding button in its browsing session.
- If the page updated within the headless browser's session, then the page within the iFrame would update in the same way.

I'm wondering if I might be able to achieve this using docker-selenium However, I'm guessing this would involve me embarking on a lengthy process of adapting both your container and my app, so before I dig too far into this potential rabbit warren, can I ask: is something like this even possible?

**Comment by elgalu** [comment]
It seems quite simple, just follow the [noVNC](https://github.com/elgalu/docker-selenium#novnc) section in the README then embed in an iframe [localhost:6080/vnc.html](http://localhost:6080/vnc.html)

Replace `localhost` with the proper IP, i.e. `docker-machine ip default` if you are on Mac.

**Comment by elgalu** [comment]
@snoblenet do you want to keep this issue open? or perhaps send a PR updating the docs on how to embed the iframe? did my comment helped at all?

**Comment by snoblenet** [comment]
No I'll close thanks. I was comparing the feasibility of building several different features that would meet a similar need. I'll eventually build the feature that requires what we were discussing, so thanks for confirming that it's feasible. However, I've since prioritising the building of a different feature that does not require this, so I've not yet tested what you described.
