### ISSUE TITLE
Release from CI

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#70]
Now #66 is done what is missing is to upgrade the git release from Travis also

https://developer.github.com/v3/repos/contents/#update-a-file
https://docs.travis-ci.com/user/deployment/releases/
http://stackoverflow.com/questions/5207269/releasing-a-build-artifact-on-github
https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by diemol** [comment]
I thought this was already done, right?

**Comment by elgalu** [comment]
What's still missing is to update the release page after every release:
https://github.com/elgalu/docker-selenium/releases

Right now I do this manually

**Comment by elgalu** [comment]
But is low prio so will close for now
