### ISSUE TITLE
Grid plugin: docker management

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#78]
Use the grid plugin to:

- create a new container when a new selenium session is created
- destroy the container the the selenium session is deleted

Ref:
https://github.com/docker-java/docker-java

**Comment by elgalu** [comment]
@diemol is working on this, updates will be posted here later on

**Comment by diemol** [comment]
Zalenium is already open source with its first release, you can try it out.
https://github.com/zalando-incubator/zalenium

**Comment by elgalu** [comment]
Works!!!!!
