### ISSUE TITLE
Grid plugin: FWD non matched capabilities to cloud providers

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#79]
- Parse requested browser capabilities and if not available in docker (e.g. not Chrome nor Firefox) then FWD it to Sauce Labs or BrowserStack.

Ref:
https://github.com/rossrowe/sauce-grid-plugin/wiki#usage
http://sauceio.com/index.php/2012/09/introducing-the-sauce-plugin-for-selenium-grid/

**Comment by elgalu** [comment]
FYI @diemol is working on this, there will be an update here later on

**Comment by diemol** [comment]
Zalenium is already open source with its first release, you can try it out.
https://github.com/zalando-incubator/zalenium

**Comment by elgalu** [comment]
Works!!!! awesome @diemol
