### ISSUE TITLE
Tag missing from hub

### ISSUE THREAD

**Issue by amitaibu** [elgalu/docker-selenium#93]
We can no longer do `docker pull elgalu/selenium:v2.46.0-base1` - was this tag removed for a reason?

**Comment by elgalu** [comment]
Sorry @amitaibu I removed some old images, if you really want to use that one you are going to have to build it from source code:
https://github.com/elgalu/docker-selenium/tree/v2.46.0-base1

But instead I would suggest you to take this chance to upgrade:
https://github.com/elgalu/docker-selenium#run

**Comment by amitaibu** [comment]
Ok, I'll have to rebuild some parts of Shoov around it. Thanks for the quick answer!

**Comment by amitaibu** [comment]
I'm actually using now your [suggestion](https://github.com/elgalu/docker-selenium/tree/v2.46.0-base1#option-1---use-immutable-image-digests) of getting the tag with its `sha` :)
