### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#97]
Explore the use of alpine to reduce the image size, see https://github.com/SeleniumHQ/docker-selenium/pull/224

**Comment by shouze** [comment]
Should close #161 & #169.

**Comment by elgalu** [comment]
Whomever works on this, check also: https://github.com/SUNx2YCH/docker-alpine-selenium

**Comment by shouze** [comment]
@elgalu thx, interesting!

**Comment by elgalu** [comment]
Closed via https://github.com/elgalu/docker-selenium/compare/3.0.1c...3.0.1d#diff-3254677a7917c6c01f55212f86c57fbfR36

[Previous](https://github.com/elgalu/docker-selenium/releases/tag/3.0.1c) image size: **2.94 GB**
[New](https://github.com/elgalu/docker-selenium/releases/tag/3.0.1d) image size: **1.273 GB**
