### ISSUE TITLE
Add Internet Explorer

### ISSUE THREAD

**Issue by elgalu** [elgalu/docker-selenium#99]
Follow this at https://github.com/Microsoft/Virtualization-Documentation/issues/214

**Comment by sgerhardt** [comment]
@elgalu Unfortunately https://github.com/Microsoft/Virtualization-Documentation/issues/214 has been closed. Not sure if all hope is lost or if there are other approaches we can pursue...

**Comment by elgalu** [comment]
For now hope is lost as I don't intend to run IE in a virtual machine inside docker, at least not in this project so closing...
